### ISSUE TITLE
Jack Transport Master behaviour is very "jumpy"

### ISSUE THREAD

**Issue by danielappelt** [ahlstromcj/sequencer64#10]
This report might be seen as a follow up to #8. I am trying to use sequencer64 as transport master for jack under Arch Linux. When I hit play in sequencer64, the playroll visualization in the top right corner of the main window is jumping around very wildly.

In the simplest setup, I just start these applications:

- jack2 via jackdbus
- qjackctl
- sequencer64

In the options, I have just ticked the checkbox for "Transport Master". If I hit play in sequencer64, I get the jumpy behavior as described above. There is no position indicator moving at all in the editor window. In qjackctl, the BBT display is also jumping, but that might be more or less okay as the value is at least steadily increasing. If I go down to 20bpm in sequencer64, suddenly I can see the position indicator jumping around in the pattern editor.

If, in addition, I send Midi clock signals from sequencer64 to Rebirth (running under wine), Rebirth is syncing to a tempo of 500bpm while I was expecting to see 104bpm which I have set in sequencer64. This might explain the jumpy behavior described above. The same setup works fine without synchronizing the jack transport that is if no jack transport checkbox is ticked in the options.

In seq24, jack transport synchronization worked better (mostly). Seq24 does not send correct Midi clock signals though.

**Comment by danielappelt** [comment]
I just did a further test with the metronome [klick](http://das.nasophon.de/klick/). In addition to the simple setup, I start it like this:

`klick -j -P`

where -j means "follow jack transport BBT info (no tempo map)". This indeed leads to the correct result with respect to the metronome!

So, for now, this just leaves me with two issues when using the jack transport master option:

- Midi clock signals seem to be wrong
- visualisations are jumpy

**Comment by ahlstromcj** [comment]
Thanks for the bug report!  I had noticed the jumpiness in the "pill bar"
(they call the black progress box "the pill"), but let it go, so I'll be
sure to follow up on that.  I think I've also seen the progress bar jump
sometimes.

As for the MIDI clocks, I'll have to get up to speed on that.  How do you
tell seq24/64 to send clock signals?  What's "wrong" with them?

Finally, can you give some detail about how JACK transport sync works better
in seq24?  I.e. what are the symptoms in seq64?

Thanks!  Love these reports!  I want to preserve the spirit of seq24 and
yet make it better and better.

Chris

-------- Daniel Appelt 14:47 Tue 19 Jan      --------

>This report might be seen as a follow up to #8 I am trying to use
>sequencer64 as transport master for jack under Arch Linux When I hit play
>in sequencer64, the playroll visualization in the top right corner of the
>main window is jumping around very wildly
>
>In the simplest setup, I just start these applications:
>
>- jack2 via jackdbus
>- qjackctl
>- sequencer64
>
>In the options, I have just ticked the checkbox for "Transport Master" If I
>hit play in sequencer64, I get the jumpy behavior as described above There
>is no position indicator moving at all in the editor window In qjackctl,
>the BBT display is also jumping, but that might be more or less okay as
>the value is at least steadily increasing If I go down to 20bpm in
>sequencer64, suddenly I can see the position indicator jumping around in
>the pattern editor
>
>If, in addition, I send Midi clock signals from sequencer64 to Rebirth
>(running under wine), Rebirth is syncing to a tempo of 500bpm while I was
>expecting to see 104bpm which I have set in sequencer64 This might explain
>the jumpy behavior described above The same setup works fine without
>synchronizing the jack transport that is if no jack transport checkbox is
>ticked in the options
>
>In seq24, jack transport synchronization worked better (mostly) Seq24 does
>not send correct Midi clock signals though
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/10

-- 
Q:	How many Oregonians does it take to screw in a light bulb?
A:	Three.  One to screw in the light bulb and two to fend off all those
	Californians trying to share the experience.

**Comment by danielappelt** [comment]
The setup options for MIDI realtime clock are to be found on the first option's page. For each MIDI port you should see three radio choices. In sequencer64, the clock signals are send as expected if there sync to jack transport is not enabled, i.e. none of the respective checkboxes is set on the last option's page. This already is an improvement with respect to seq24 where the MIDI clock signals seemed to be always wrong!

In seq24, the jack transport options work "better" while they are not providing BBT information. There is no jumpiness in the pill bar or the position cursor in the pattern editor regardless of which checkboxes are set for jack transport sync.

What I don't understand - maybe because of lack of knowledge of the overall jack architecture - is how enabling jack transport master option may interfere with the timing of the visuals and MIDI clock send out from sequencer64. I thought, in this case, it would just be a matter of updating the jack server in regular intervals about the current play position, i.e. a one way communication towards the jack server.

**Comment by ahlstromcj** [comment]
Okay, I know what you mean now.  I haven't messed with those.

I may have found the bug.  There's a place where I took

   current_tick = current_tick - size;

and changed it to 

   current_tick -= - size;

instead of

   current_tick -= size;

Won't know for sure until I can get home and run the code, tonight.
One of my "rare" fat-fingered bugs, as opposed to a bug caused
by a lack of understanding.

I've almost got PPQN values other than 192 working, by the way.
I'm thinking going as high as 960 PPQN is enough, though I've
heard some people want outrageously high values.  What do you think?

Chris

-------- Daniel Appelt 09:02 Wed 20 Jan      --------

>The setup options for MIDI realtime clock are to be found on the first
>option's page. For each MIDI port you should see three radio choices. In
>sequencer64, the clock signals are send as expected if there sync to jack
>transport is not enabled, i.e. none of the respective checkboxes is set on
>the last option's page. This already is an improvement with respect to
>seq24 where the MIDI clock signals seemed to be always wrong!
>
>In seq24, the jack transport options work "better" while they are not
>providing BBT information. There is no jumpiness in the pill bar or the
>position cursor in the pattern editor regardless of which checkboxes are
>set for jack transport sync.
>
>What I don't understand - maybe because of lack of knowledge of the overall
>jack architecture - is how enabling jack transport master option may
>interfere with the timing of the visuals and MIDI clock send out from
>sequencer64. I thought, in this case, it would just be a matter of updating
>the jack server in regular intervals about the current play position, i.e.
>a one way communication towards the jack server.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/10#issuecomment-173274712

-- 
A horse!  A horse!  My kingdom for a horse!
		-- Wm. Shakespeare, "Richard III"

**Comment by danielappelt** [comment]
I tried to apply your fix yesterday, unfortunately, to no avail as it seemed. I will have more time to look into this the following days.

**Comment by danielappelt** [comment]
Regarding PPQN, I guess it wouldn't hurt to allow arbitrarily high values. Supporting extreme value ranges could make it easier to reveal further bugs. I would suggest to do the same for the BPM setting where the lowest setting currently is 20. In my opinion, one should be able to go all the way down to 1 BPM if desired.

**Comment by ahlstromcj** [comment]
Thanks for the feed back!  Yeah, my little fix was for a legitimate bug, but
not THE bug.   Without jack, the maintime idle_progress() ticks go up by
about 10 each time; with it, they go up by about 20000!  Haven't seen
why the jack_ticks_delta is so high.  Sigh.

-------- Daniel Appelt 00:43 Thu 21 Jan      --------

>Regarding PPQN, I guess it wouldn't hurt to allow arbitrarily high values. Supporting extreme value ranges could make it easier to reveal further bugs. I would suggest to do the same for the BPM setting where the lowest setting currently is 20. In my opinion, one should be able to go all the way down to 1 BPM if desired.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/10#issuecomment-173500287

-- 
I dote on his very absence.
		-- William Shakespeare, "The Merchant of Venice"

**Comment by ahlstromcj** [comment]
I went down to 2 for the BPM, and up to 19200 (10 times what qjackctl seems
to set up by default) for the PPQN.

Also, I found I had bolluxed the order of parameters in the call to
delta_time_us_to_ticks() in the perform module, which might explain the
jerky-pill (and jerky patterns) bug. 

I fixed it in the "fixups" branch, but cannot verify until tonight.

-------- Daniel Appelt 00:43 Thu 21 Jan      --------

>Regarding PPQN, I guess it wouldn't hurt to allow arbitrarily high values. Supporting extreme value ranges could make it easier to reveal further bugs. I would suggest to do the same for the BPM setting where the lowest setting currently is 20. In my opinion, one should be able to go all the way down to 1 BPM if desired.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/10#issuecomment-173500287

-- 
You will live a long, healthy, happy life and make bags of money.

**Comment by ahlstromcj** [comment]
Still an issue, even with the fix.  Found that I had somehow based the jack timebase callback on an old (0.8.7!!! how???) version of seq24, so will work on that.  See the fixups branch.

**Comment by ahlstromcj** [comment]
I changed the lowest BPM, now ranges from 1 to 500.  Will check this into
fixups tomorrow, test some more, and then merge to master along with the
JACK fix.  Also just fixed the Options UI to allow only valid combinations
of JACK settings (you can still screw them up in the 'rc' file, though :-)

PPQN now ranges from 32 to 19200.  I've been testing a little bit with
reading in a 192 PPQN tune into Sequencer64 running at 384 PPQN, and 
it basically seems to work.  But a lot more corner cases to be tested!

-------- Daniel Appelt 00:43 Thu 21 Jan      --------

>Regarding PPQN, I guess it wouldn't hurt to allow arbitrarily high values. Supporting extreme value ranges could make it easier to reveal further bugs. I would suggest to do the same for the BPM setting where the lowest setting currently is 20. In my opinion, one should be able to go all the way down to 1 BPM if desired.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/10#issuecomment-173500287

-- 
Q:	What do you say to a New Yorker with a job?
A:	Big Mac, fries and a Coke, please!

**Comment by danielappelt** [comment]
Hi Chris! This looks much better now in the fixups branch. The following things are now working for me:

- jack transport gets started and stopped as expected if sequencer64 ist transport master
- sequencer64 gets started and stopped as expected if qjackctl or carla are used as transport master
- Midi realtime clock messages seem to be correct, Midi start / stop messages are sent as expected

What does not work:

- BBT values in jack do not seem to get updated. In qjackctl the "Transport BBT" display always stays at "1.1.000". I guess this is the reason why "klick -j -P" just produces a single long square wave sound as it is waiting for further BBT updates to play more sounds.

Overall, it now seems to be usable together with other/external Midi sequencers.

**Comment by ahlstromcj** [comment]
I got "klick -j -P" to run without aborting once seq64 started by enabling
some code that was disabled in seq24. Seq24 also aborts, I found.

I've pulled out this code into its own function and will see if I can use it
elsewhere to update the BBT.  See the new function
jack_assistant::set_position(), which will be in soon.

Once I commit that, I'll merge.

Chris

-------- Daniel Appelt 15:22 Sun 24 Jan      --------

>Hi Chris! This looks much better now in the fixups branch. The following things are now working for me:
>
>- jack transport gets started and stopped as expected if sequencer64 ist transport master
>- sequencer64 gets started and stopped as expected if qjackctl or carla are used as transport master
>- Midi realtime clock messages seem to be correct, Midi start / stop messages are sent as expected
>
>What does not work:
>
>- BBT values in jack do not seem to get updated. In qjackctl the "Transport BBT" display always stays at "1.1.000". I guess this is the reason why "klick -j -P" just produces a single long square wave sound as it is waiting for further BBT updates to play more sounds.
>
>Overall, it now seems to be usable together with other/external Midi sequencers.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/10#issuecomment-174351780

-- 
Debian Hint #11: Keep up to date on what's going on - read the Debian
Project News. Read it on the web at http://www.debian.org/News/weekly/

**Comment by ahlstromcj** [comment]
Okay, I found an example in the sooperlooper project, and am trying it out
in jack_assistant.cpp (look for the USE_ORIGINAL_TIMEBASE_CALLBACK macro)
in the "fixups" branch.

It makes the "klick -j -P" metronome work, and seems to work with Hydrogen
as well, when Sequencer64 is JACK Master and Hydrogen is not.
I still have more testing to do and also want to understand the differences
between the old and new code, before I merge.  Note that this seems
to be an improvement lacking in seq24.

-------- Daniel Appelt 15:22 Sun 24 Jan      --------

>Hi Chris! This looks much better now in the fixups branch. The following things are now working for me:
>
>- jack transport gets started and stopped as expected if sequencer64 ist transport master
>- sequencer64 gets started and stopped as expected if qjackctl or carla are used as transport master
>- Midi realtime clock messages seem to be correct, Midi start / stop messages are sent as expected
>
>What does not work:
>
>- BBT values in jack do not seem to get updated. In qjackctl the "Transport BBT" display always stays at "1.1.000". I guess this is the reason why "klick -j -P" just produces a single long square wave sound as it is waiting for further BBT updates to play more sounds.
>
>Overall, it now seems to be usable together with other/external Midi sequencers.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/10#issuecomment-174351780

-- 
Never reveal your best argument.

**Comment by danielappelt** [comment]
I can confirm that the pill bar and BBT transfer to jack now seem to work as expected. Unfortunately, MIDI realtime messages are no longer sent correctly if sequencer64 is connected to jack. I will open a new issue for this and close this one for now.

**Comment by ahlstromcj** [comment]
Okay. Can you explain a little more about what exactly is happening?  Are
these messages from files or from instruments?   I wonder if it's related
to the klick fix. Thanks!

**Comment by danielappelt** [comment]
I have just tested version 0.9.9.16 and most of the problems seem to be gone now!

There is only one thing left. If you stop the transport (sequencer64 is transport master), and you use qjackctl or the carla / catia transport functions to roll back transport to the beginning, and then start play back again from one of those tools, the BPM information seems to be gone. The behaviour is the same when using either qjackctl or carla or catia. For example, BPM in qjackctl is then set to "6.953e-310", in catia it is displayed as "0" after rolling back.

In general, the "roll back" should be added as a feature to sequencer64 - maybe it is there but I don't know where.

**Comment by ahlstromcj** [comment]
Also needed is proper pause functionality, I think.  Meanwhile, I'm dabbin
my tears due to the Panthers Superbowl loss :-)

-------- Daniel Appelt 16:04 Sun 07 Feb      --------

>I have just tested version 0.9.9.16 and most of the problems seem to be gone now!
>
>There is only one thing left. If you stop the transport (sequencer64 is transport master), and you use qjackctl or the carla / catia transport functions to roll back transport to the beginning, and then start play back again from one of those tools, the BPM information seems to be gone. The behaviour is the same when using either qjackctl or carla or catia. For example, BPM in qjackctl is then set to "6.953e-310", in catia it is displayed as "0" after rolling back.
>
>In general, the "roll back" should be added as a feature to sequencer64 - maybe it is there but I don't know where.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/10#issuecomment-181144785

-- 
It is a wise father that knows his own child.
		-- William Shakespeare, "The Merchant of Venice"

**Comment by ahlstromcj** [comment]
Well, found out I left some settings out of the JACK timebase callback,
from sooperlooper.  Tested the basics, but I have to add some code to
pass along some variables (e.g. beats per minute).  Then qjackctl will
get the right data from Sequencer64.

-------- Daniel Appelt 16:04 Sun 07 Feb      --------

>I have just tested version 0.9.9.16 and most of the problems seem to be gone now!
>
>There is only one thing left. If you stop the transport (sequencer64 is transport master), and you use qjackctl or the carla / catia transport functions to roll back transport to the beginning, and then start play back again from one of those tools, the BPM information seems to be gone. The behaviour is the same when using either qjackctl or carla or catia. For example, BPM in qjackctl is then set to "6.953e-310", in catia it is displayed as "0" after rolling back.
>
>In general, the "roll back" should be added as a feature to sequencer64 - maybe it is there but I don't know where.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/10#issuecomment-181144785

-- 
The bone-chilling scream split the warm summer night in two, the first
half being before the scream when it was fairly balmy and calm and
pleasant, the second half still balmy and quite pleasant for those who
hadn't heard the scream at all, but not calm or balmy or even very nice
for those who did hear the scream, discounting the little period of time
during the actual scream itself when your ears might have been hearing it
but your brain wasn't reacting yet to let you know.
		-- Winning sentence, 1986 Bulwer-Lytton bad fiction contest.

**Comment by danielappelt** [comment]
Seems to be working as of version 0.9.9.17.
