### ISSUE TITLE
seq64 no longer shows up as client when started through ladish

### ISSUE THREAD

**Issue by simonvanderveldt** [ahlstromcj/sequencer64#100]
I'm not 100% sure what's causing this, but what's happening is that when I start sequencer64 through ladish it no longer shows up as a client in a ladish studio or room. I did a git bisect and this started with commit 702a431ced43b542c1c205258325a0c5a373c88b.

For the commit 0fe456d3f610b9238860416cf46a36a4e566876f before the broken one this is the result when I add sequencer64 to a ladish room (the same happens when adding it to a studio):
![image](https://user-images.githubusercontent.com/204286/28491001-0ac22636-6ee8-11e7-84bf-d8e97c7c4910.png)
I.e. sequencer64 is visible in the ladish room and can be connected to the other clients.

And for commit 702a431ced43b542c1c205258325a0c5a373c88b this is the result
![image](https://user-images.githubusercontent.com/204286/28491062-bb51db94-6ee9-11e7-9347-4c9f52ef8333.png)
I.e. sequencer64 isn't visible inside the ladish room, which means it's impossible to use it together with ladish.

**Comment by ahlstromcj** [comment]
Will check it out! Thanks!

**Comment by ahlstromcj** [comment]
Make sure you are using the "manual" (i.e. virtual) ports option.  It's "-m" on the command-line.  Seq64 seems to be doing what it should in qjackctl; I tried ladish but obviously need to figure out how it works.  I didn't see anything obviously wrong using "git difftool" on the two commits you note above.

**Comment by simonvanderveldt** [comment]
@ahlstromcj Running sequencer64 with or without `-m` doesn't make a difference for me.

It seems to only happen when starting seq64 through ladish, doesn't matter if you add it to a studio or a room.
When starting seq64 directly it does show up in the ladish studio. But I guess this is to be expected because the studio simply shows all jack clients similar to qjackctl/patchage/catia.

The only thing I can currently guess is that it might be a timing issue? I.e. it now takes seqeuencer64 somewhat longer to create the actual jack client and because of that is now no longer being picked up by ladish? This is just guessing though, I don't even know if ladish is sensitive to a timing issue like this.

**Comment by ahlstromcj** [comment]
Hmmm, there is one change that affects timing at startup.  What branch you
running? Master?

**Comment by simonvanderveldt** [comment]
> Hmmm, there is one change that affects timing at startup.  What branch you
> running? Master?

Currently I'm using 0.91.0 because that version still works.
But if you want me to test something I can build/install/run any commit or branch.

**Comment by ahlstromcj** [comment]
I push a fix to the tempo_track branch.  If you don't want that branch, you can edit Seq64rtmidi/seq64rtmidi.cpp;  move this call from after the creation of the mainwnd to before it:

p.launch(seq64::usr().midi_ppqn());

I currently have that line just before "if (seq64::usr().inverse_colors())" for the (hopeful) fix.

And cross your fingers :-)

**Comment by ahlstromcj** [comment]
By the way, what's broken for you in versions after 0.91.0?  Thanks!

**Comment by simonvanderveldt** [comment]
> I push a fix to the tempo_track branch. If you don't want that branch, you can edit Seq64rtmidi/seq64rtmidi.cpp; move this call from after the creation of the mainwnd to before it:
> 
> p.launch(seq64::usr().midi_ppqn());
> 
> I currently have that line just before "if (seq64::usr().inverse_colors())" for the (hopeful) fix.
> 
> And cross your fingers :-)

I cherry picked the commit that reverted/fixed this (https://github.com/ahlstromcj/sequencer64/commit/fd5567684ffb4fc9926f7b57befa84675b470ad7) and it's now working again :tada: 
So yeah, apparently there's some sensitivity to timing there.

> By the way, what's broken for you in versions after 0.91.0? Thanks!

Only this issue, no other problems :)

**Comment by simonvanderveldt** [comment]
Just noticed this has been merged into master, just built it and it's working as it should.
Thanks again!
