### ISSUE TITLE
Pattern Editor / Piano Roll: new notes are played, but there's no Note Off if Interaction Method is set to Fruity

### ISSUE THREAD

**Issue by pixelrust** [ahlstromcj/sequencer64#105]
I haven't read in details all existing issues, but it seems this has not been reported yet.

This was reproduced on multiple MIDI channels, by using external hardware synths and drum machines - not plugins or virtual synths.

seq64 v "0.93.1 pending"

- if needed, set Interaction Method to "Fruity" and restart seq64
- create a new pattern, set the appropriate MIDI channel and verify you get sound
- if needed, choose an instrument with a noticeable sustain, like strings
- in Pattern Editor verify that the Piano Roll behaves as expected: a note starts when you click them, keeps being played while you keep the mouse button pressed, and ends after you release it
- left-click the grid and add a note 

expected behaviour:
- the note is played
- the note only continues while you keep the mouse button pressed
- if you release the mouse button, the note stops

what happens:
- the note sound continues even after you release the mouse button, as if there was no Note Off event

Now, while the first note is still being played, move the pointer over the Piano Roll without clicking.

expected behaviour:
- nothing

what happens:
- one or more random notes are played (including their Note Off event, apparently)
- the first note that was previously being played finally stops

Notes:
- after this, the behaviour can be reproduced again and again by adding new notes
- I couldn't reproduce this problem when setting Interaction Method to "seq24"
- I don't know if Seq24 is affected by this issue
- I suspect this wasn't affecting the 0.9.3 version but I'm not sure about it

**Comment by ahlstromcj** [comment]
Great detail!  Will take me awhile to check that one!  :-)

**Comment by ahlstromcj** [comment]
I think I got it, a listen-press event was occurring when a listen-release event was needed.  Let me know of any other issues related to fruity mode.

**Comment by ahlstromcj** [comment]
Okay, verified this in latest version 0.94.3, fixed.
