### ISSUE TITLE
Segfault on startup

### ISSUE THREAD

**Issue by muranyia** [ahlstromcj/sequencer64#109]
Built the latest trunk with vanilla bootstrap, configure, make. With or without JACK running, I get
```
[Initialized, running without JACK sync]
Segmentation fault (core dumped)
```
For `sequencer64 --help` I get
```
*** stack smashing detected ***: sequencer64 terminated
Aborted (core dumped)
```
This is not happening if I `./configure --enable-alsamidi`.

BTW, `sequencer64 -o sets=8x8` gives me `sequencer64: invalid option -- 'o'`

What do I need to be able to use `-o sets=RxC`?

**Comment by ahlstromcj** [comment]
Well, I can't get a segfault on my setup with the latest from master or tempo_track, so, if you can, get me more info about your setup:  JACK running?  Config files in place?  Song loaded?  Etc, whatever you can brainstorm.

I built the alsamidi version, and I can't get the segfault for sequencer64.  I can duplicate the -o issue, so I can fix that real soon.  I haven't been paying much attention to the alsamidi version, but it's worthwhile to keep that up-to-date.

Thanks for the report, we will get to the bottom of this!  :-)

**Comment by muranyia** [comment]
The crash happened when starting seq64, so no song was loaded yet, and the same with or without JACK running.
I had a feeling I was missing a lib, so I went and installed `librtmidi-dev` and the resulting build doesn't crash. Seems dependence checking is not catching this?

**Comment by ahlstromcj** [comment]
Weird!  The "rtmidi" that Sequencer64 (seq64) uses is actually our own version of rtmidi, completely refactored.  "ldd ./Seq64rtmidi/seq64" shows no dependency on librtmidi.  I uninstalled librtmidi-dev and librtmidi3, and still cannot duplicate the issue.

You could install ltrace and strace, use them to run seq64, and see what it is trying to do when it bugs out.  Another option is to move your ~/.config/sequencer64 directory and see if the crash still occurs.

I have pushed some build fixes to the latest in the tempo_track branch, but I don't think they would matter for your issues.

Odd stuff.  I'll be installing KX Studio in a VM to further explore the build issues.

**Comment by muranyia** [comment]
Uninstalled `librtmidi-dev`and `librtaudio-dev`(which was installed as a dependency of the former), did `make clean`, rebuilt - no crash!
I will definitely make a trace if a crash happens in the future.
