### ISSUE TITLE
Midi realtime clock messages are not in sync

### ISSUE THREAD

**Issue by danielappelt** [ahlstromcj/sequencer64#11]
With the current release 0.9.9.15, Midi realtime clock messages are broken again when connected to jack. Currently, it seems that if sequencer64 is transport master, the realtime clock messages indicate a much slower tempo than set in sequencer64. If sequencer64 is jack transport "slave", the realtime clock messages seem to indicate a much faster tempo.

This was tested only against ReBirth windows application running on wine using an ALSA Midi through port for communication from sequencer64 to wine/ReBirth.

In theory, the problem should also be visible using a MIDI monitor application connected to an ALSA Midi port that receives clock signals from sequencer64 (via first tab in options panel) .

**Comment by danielappelt** [comment]
There should be 24 realtime clock signals in every quarter note when sequencer64 is playing (see SEQ64_MIDI_CLOCK_IN_PPQN).

**Comment by ahlstromcj** [comment]
Do you know in which version it worked? That would help me focus on the
offending code. Thanks!

**Comment by danielappelt** [comment]
It works in 0.9.9.14 - I tested commit `a4101685cd91a033450a13f70dc1208992881bd6` - if sequencer64 is jack transport master. Transport needs to be started from sequencer64 in this case. I checked the diffs between this commit and the current release but for me the changes/involved files were too complex.

**Comment by ahlstromcj** [comment]
Great!  That'll make it easier to crack. Yeah, the fix to klick support
taken from sooperlooper is probably the culprit.  The commit number ought
to nail  it.  Might take me a couple evenings ....

**Comment by ahlstromcj** [comment]
You can check out the latest fixups (commit 53f56a37...) and define
USE_ORIGINAL_TIMEBASE_CALLBACK in jack_assistant.cpp to see if the old code
corrects the MIDI Clock.  (It will cause klick -j -P to iterate too rapidly,
though.)

You can also define USE_SEQ24_0_9_3_CODE in perform.cpp to see if the
new code (!) from seq24 0.9.3 (it's alive!) is causing the issue.
It tries to prevent clock drift, but maybe it causes a speed issue.

Note that both macros are currently #undef'd.

No hurry, no worry if you can't get to it for awhile.

Also note that sequencer64 now saves the Time Signature data in the
conventional manner.  It can define MIDI clock values other than 24.

-------- Daniel Appelt 15:42 Tue 02 Feb      --------

>It works in 0.9.9.14 - I tested commit `a4101685cd91a033450a13f70dc1208992881bd6` - if sequencer64 is jack transport master. Transport needs to be started from sequencer64 in this case. I checked the diffs between this commit and the current release but for me the changes/involved files were too complex.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/11#issuecomment-178890320

-- 
I've touch'd the highest point of all my greatness;
And from that full meridian of my glory
I haste now to my setting.  I shall fall,
Like a bright exhalation in the evening
And no man see me more.
		-- Shakespeare

**Comment by ahlstromcj** [comment]
Well, how can I set up a monitor?  I tried playing with Qtractor, but no
matter what timing settings I used in it, it always followed Sequencer64
exactly, as far as I could tell.  Even if I enabled the suspect seq24 0.9.3
patch.  So maybe it was following JACK the whole time.

What MIDI monitor app do you recommend for testing this bug?  I'd really
prefer to avoid WINE.  I do have a consumer keyboard that looks like it
implements MIDI Clock, but haven't had a chance to set it up.

By the way, I can pretty reliably get qtractor to crash with a "Floating
point exception".  Heh, it took me some work to clean those out of
Sequencer64's JACK code :-)

-------- Daniel Appelt 15:22 Tue 02 Feb      --------

>With the current release 09915, Midi realtime clock messages are broken again when connected to jack Currently, it seems that if sequencer64 is transport master, the realtime clock messages indicate a much slower tempo than set in sequencer64 If sequencer64 is jack transport "slave", the realtime clock messages seem to indicate a much faster tempo
>
>This was tested only against ReBirth windows application running on wine using an ALSA Midi through port for communication from sequencer64 to wine/ReBirth
>
>In theory, the problem should also be visible using a MIDI monitor application connected to an ALSA Midi port that receives clock signals from sequencer64 (via first tab in options panel)
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/11

-- 
You're a card which will have to be dealt with.

**Comment by danielappelt** [comment]
I am using [GMIDImonitor](http://home.gna.org/gmidimonitor/) which is a very basic monitoring tool together with qjackctl. GMIDImonitor needs to be started with option `--alsa` for it to work with ALSA midi ports. qjackctl is used to create ALSA midi connections and to test jack slave mode in sequencer64. For my tests I use an ALSA "Midi Through Port" whose output is patched to GMIDImonitor. Furthermore, you need to create a pattern in sequencer64 containing only quarter notes.
The output that is to be expected is that you will see 24 "MIDI Real Time Clock" messages in between two adjacent quarter notes. Unfortunately, right now I am not seeing any notes at all being sent from sequencer64 - I am using the commit that I mentioned earlier.

**Comment by ahlstromcj** [comment]
Thanks for the test setup. How did I "jack" it up so badly? :-(

**Comment by ahlstromcj** [comment]
Can you attach or check-in (to "contrib") your sequencer64.rc file?

I'm having odd troubles with qjackctl; it won't always make a connection,
either with seq24 or 64.

-------- Daniel Appelt 14:39 Thu 04 Feb      --------

>I am using [GMIDImonitor](http://home.gna.org/gmidimonitor/) which is a very basic monitoring tool together with qjackctl. GMIDImonitor needs to be started with option `--alsa` for it to work with ALSA midi ports. qjackctl is used to create ALSA midi connections and to test jack slave mode in sequencer64. For my tests I use an ALSA "Midi Through Port" whose output is patched to GMIDImonitor. Furthermore, you need to create a pattern in sequencer64 containing only quarter notes.
>The output that is to be expected is that you will see 24 "MIDI Real Time Clock" messages in between two adjacent quarter notes. Unfortunately, right now I am not seeing any notes at all being sent from sequencer64 - I am using the commit that I mentioned earlier.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/11#issuecomment-180084869

-- 
Do nothing unless you must, and when you must act -- hesitate.

**Comment by danielappelt** [comment]
I have now also checked the latest version from the fixups branch. With GMIDImonitor, the results do not look so different - there is still no note data appearing in the monitor. This is my latest [sequencer64.rc](https://gist.github.com/danielappelt/b292d21bb82faa9debd8). Please note that I have never deleted the .rc or .usr files during my tests. Every time I checked, these files looked okay. I would not be surprised though if there are some interdependencies between those files and the parameters that you may provide via the command line.

**Comment by ahlstromcj** [comment]
I just want to make sure I'm duplicating your setup.  If the latest commit
fails, too, it's probably the sooperlooper code I tried. Thanks!

**Comment by ahlstromcj** [comment]
Okay, I got the setup working, and the latest "fixups" checkout seems to
work the same as far as the clock goes.  I'm going to quit tonight, though.
Getting tired.  But here's what I did to see notes.

First, I used "midisnoop" instead of "gmidimonitor".  It shows count number
and the timestamps as well.  I don't think this is relevant to the results,
just easier to see what's happening and make tick-calculations.

Second, I hooked the MIDI Through Port-0 to midisnoop's "MIDI input".
I configured midisnoop with Driver = ALSA Sequencer, Input Port =
MIDI Through 14:0, Output Port = none, and I unchecked "Ignore Time Events".

Third, after running seq24 or sequencer64 ("fixups" latest) and loading
the contrib/midi/click_4_4.midi file, I also opened the Song Editor
and layed down a few copies of the pattern.  That was the key to actually
seeing notes, I think.  I also enabled the "input goes to output" button,
but I doubt that was the key.

Anyway, I'm getting 24 clocks per quarter note with the latest code.
The time values midisnoop shows are "timestamps", not tick numbers.
There are about 500 timestamps per quarter note, the BPM is 120.

So right now I think the code is working, but I will hack at it again
tomorrow to be sure, when my eyes aren't so bleary.

-------- Daniel Appelt 17:02 Thu 04 Feb      --------

>I have now also checked the latest version from the fixups branch. With GMIDImonitor, the results do not look so different - there is still no note data appearing in the monitor. This is my latest [sequencer64.rc](https://gist.github.com/danielappelt/b292d21bb82faa9debd8). Please note that I have never deleted the .rc or .usr files during my tests. Every time I checked, these files looked okay. I would not be surprised though if there are some interdependencies between those files and the parameters that you may provide via the command line.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/11#issuecomment-180132349

-- 
question = ( to ) ? be : ! be;
		-- Wm. Shakespeare

**Comment by danielappelt** [comment]
Obviously, it was also a little bit too late in the evening for me as well. What I did not realize is that in the sequencer64 options, "Jack Start mode" was not set to "Live Mode" which is needed to have patterns being played without using the song editor.
Anyway, using the latest fixups branch everything seems to be working as expected regarding the Midi clock signals. What I don't see currently, are BBT updates, i.e. the BBT display in qjackctl does not change. Do I have to enable one of the defines that you mentioned earlier in order to make it work?

**Comment by ahlstromcj** [comment]
I see the BBT updating, but I built with the defines as they are in the
code:

jack_assistant.hpp:#undef  USE_SEQ24_0_9_3_CODE
                   #define USE_JACK_SYNC_CALLBACK

There's too many of these USE macros, so I will spend some time this weekend
to get rid of some of them, and I will re-enable the the seq24 0.9.3 MIDI clock
drift patch and test thoroughly, and if it all works out, tag a new version.

As for the "Live" mode requirement, at one time I had it so that the mode
depended on which window (song or pattern) you used to start the playback.
I changed that, but will reinvestigate and make it conform to seq24.
Not sure which way is better, and I have seen complaints about how seq24 did
it.

Dang, why can't qjackctrl keep the ticks in BBT at 4 characters the whole
time, zero padded.... the flickering is annoying.

Anyway, the bottom line is test thoroughly after every "significant" change.
No rushing :-D  

-------- Daniel Appelt 02:41 Fri 05 Feb      --------

>Obviously, it was also a little bit too late in the evening for me as well. What I did not realize is that in the sequencer64 options, "Jack Start mode" was not set to "Live Mode" which is needed to have patterns being played without using the song editor.
>Anyway, using the latest fixups branch everything seems to be working as expected regarding the Midi clock signals. What I don't see currently, are BBT updates, i.e. the BBT display in qjackctl does not change. Do I have to enable one of the defines that you mentioned earlier in order to make it work?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/11#issuecomment-180289537

-- 
Don't worry so loud, your roommate can't think.

**Comment by danielappelt** [comment]
Since version 0.9.9.16 midi realtime clock messages seem to work as expected.
