### ISSUE TITLE
Feature request: score editor

### ISSUE THREAD

**Issue by F0rth** [ahlstromcj/sequencer64#114]
Ok, this one is a long shot: a button in the piano roll window to switch to a score view/editor for people more confortable with a music sheet (yes it's a very selfish feature request :D).

**Comment by ahlstromcj** [comment]
Something to consider!  I like to let such ideas ferment / fester until my
subconscious says "do it!"

**Comment by ahlstromcj** [comment]
Sequencer64 is starting to exceed the bounds of the project intent, which is to do the stuff that seq24 does, with bug fixes, support for more features and SMF levels, allow editing some minor events that seq24 does not handle, I agree with sonejosstudios' ideo.  Editing a MIDI file as a musical score just opens a whole can of worms that would take me a very long time to master compared to people like MuseScore that alread do it well.  I will, regretfully, close this issue as "will not do".  :-(
