### ISSUE TITLE
Add a git tag for each new version

### ISSUE THREAD

**Issue by danielappelt** [ahlstromcj/sequencer64#12]
Could you please tag all future commits that correspond to a new version/release? This will help in testing / bug hunting.

**Comment by ahlstromcj** [comment]
Okay. What do you look for in a tag name?

**Comment by danielappelt** [comment]
Just tag it with the version number, i.e. "0.9.9.15". This makes it easier (at least for me) to go back in time when building the software. Furthermore, package maintainers can focus on the tagged commits and ignore the in-between ones.

**Comment by ahlstromcj** [comment]
Understood.  I'll probably forget sometimes though :-*

**Comment by danielappelt** [comment]
Thanks for supporting this! I would keep this issue open for now to have it as a reminder ;-)

**Comment by ahlstromcj** [comment]
I have documented the tagging process in contrib/notes/git.txt and have been applying it assiduously.  So I will close this one to get it out of the way of all the other open issues. :-)
