### ISSUE TITLE
Stop button does not reset samples to beginning

### ISSUE THREAD

**Issue by naclander** [ahlstromcj/sequencer64#124]
Firstly I just wanted to say thanks for all the effort you've put in to seq64, picking up where seq24 left off. I've really been using it quite a bit since discovering it after my frustration with seq24.

When compiling the latest version, I've noticed pressing the stop button doesn't reset all the sequences to the beginning. It seems to do roughly the same thing the pause button does now. I don't think this was the behavior before, is this desired?

EDIT: I may be misremembering how this worked before, so it could have been that STOP did not used to do this. However, I think my original question still stands, should stop reset the sequences back to the beginning?

**Comment by ahlstromcj** [comment]
Both Stop and Panic should reset the position to 0.  Fixed in the tempo_track branch, will merge it to master as version 0.94.2 soon.

**Comment by ahlstromcj** [comment]
Fixed in version 0.94.2.
