### ISSUE TITLE
Empty pattern boxes have no numbers

### ISSUE THREAD

**Issue by milkmiruku** [ahlstromcj/sequencer64#127]
![silver_2018-01-04-19 18 30](https://user-images.githubusercontent.com/108225/34580565-5c8c881a-f185-11e7-9a38-7355474842ae.png)

**Comment by ahlstromcj** [comment]
That's just the default look if you clear out your ~/.config/sequencer64
directory and restart seq64.

Unfortunately, some of the user-interface settings are in sequencer64.rc, and
some are in sequencer64.usr.  I gotta fix that at some point.  Anyway, this is
what you want:

    sequencer64.rc:

        [keyboard-group]

        . . . 

        1     # show_ui_sequence_key and seq measures (1 = true / 0 = false)
        1     # show sequence numbers (1 = true / 0 = false); ignored in legacy mode

The second one is the one that shows the slot numbers.  Both options are
also modifiable from the File / Option / Keyboard pane.

The other file has a lot more setting (a few are shown below) that you might be
interested in.  But note that, unlike the "rc" file, the "usr" file will not be
re-saved when seq64 exits.  However, both are saved if they don't already exist,
and give you the default look very similar to seq24.

    sequencer64.usr:

        [user-interface-settings]

        . . . 

        0       # grid_style
        1       # grid_brackets
        4       # mainwnd_rows
        8       # mainwnd_cols
        1       # use_new_font

Have fun!

**Comment by milkmiruku** [comment]
Awesome, thanks :)
