### ISSUE TITLE
Tempo forcefully saved intro first pattern

### ISSUE THREAD

**Issue by muranyia** [ahlstromcj/sequencer64#141]
It seems that tempo gets saved into the first pattern, and after deleting the event and saving the file it reappears.
It also seems that this tempo does not have anything to to any more with the tempo set in the GUI (it is insisting on 130 for me, which I've already changed some time ago to another value).

**Comment by ahlstromcj** [comment]
I'll check it out. Thanks!

**Comment by ahlstromcj** [comment]
I have removed that feature; now, if you want a tempo event, you have to add one in the event editor or log one using the button on the main window.  That makes more sense, thanks for the report.  Currently available in the active branch, qt5_reconcile, and I'll merge it when it is time for 0.94.6.

**Comment by muranyia** [comment]
I think this is solved. Thanks!
