### ISSUE TITLE
qt5_reconcile comile error with ./bootstrap -er -qt "gdkmm/cursor.h: No such file or directory"

### ISSUE THREAD

**Issue by layk** [ahlstromcj/sequencer64#166]
I get:
make[1]: *** No rule to make target '/home/lykki2/dev/seq64/current/sequencer64/seq_gtkmm2/src/.libs/libseq_gtkmm2.la', needed by 'seq64'.  Stop.
make[1]: *** Waiting for unfinished jobs....
  CXX      seq64rtmidi.o
seq64rtmidi.cpp:40:10: fatal error: gdkmm/cursor.h: No such file or directory
 #include <gdkmm/cursor.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.

Although i have /usr/include/gdkmm-2.4/gdkmm/cursor.h

**Comment by ahlstromcj** [comment]
Hmm, I fixed the build system. The latest from master or playlist should
work. Master 0.96 will be out today or tomorrow, and I will make that bug
isn't present.

**Comment by layk** [comment]
Yes master works. Closing this.
