### ISSUE TITLE
multiple midi busses?

### ISSUE THREAD

**Issue by richardhenwood** [ahlstromcj/sequencer64#168]
FYI: I'm new to linux audio, and sequencer64.

I would like to use sequencer64 so program my drums and synths. So I think that what I want to do is have different patterns outputting on different midi-busses - so I can direct these different midi signals to different components (i.e. to yoshimi and drumkv1).

When I start sequencer64 I only see one midi bus available.

So, I'm looking for help to either fix my workflow (and incorrect assumptions) or figure out how to add midi busses to sequencer64.

**Comment by ahlstromcj** [comment]
I am on vacation right now, through Friday.  In the meantime, check out the PDF manual in the Github project "sequencer64-doc".  Note that ALSA and JACK work a bit differently.  Also note that the manual option creates "virtual" ports that have to be connected "manually" (either by an ALSA or JACK connector such as Qjackctl).  Also, in the pattern editor, you can select the output MIDI buss and channel for each pattern.  

If you find the manual confusing in some ways, let me know.  I am in the process of cleaning it up and making it easier to grok.  Good luck!  Thanks for the report!

**Comment by richardhenwood** [comment]
Thanks for this. I've started using Cadence and Claudia and everything seems to just work now. Sorry for the noise.
