### ISSUE TITLE
make fails in doc/dox

### ISSUE THREAD

**Issue by muranyia** [ahlstromcj/sequencer64#17]
```
Making all in doc/dox
make[1]: Entering directory `/home/muranyia/Downloads/sequencer64/doc/dox'
make[1]: *** No rule to make target `all'.  Stop.
make[1]: Leaving directory `/home/muranyia/Downloads/sequencer64/doc/dox'
make: *** [all-recursive] Error 1
```

**Comment by ahlstromcj** [comment]
I had meant to make the documentation optional (it's mainly comments from the source code), but left it in the configuration.  See the new INSTALL file.  Let me knew if this issue is fixed to your satisfaction, or still broken.  Currently tagged as "0.9.10.1".

Thanks for the report!

**Comment by muranyia** [comment]
Thanks for the fix! It builds OK now.
