### ISSUE TITLE
Hotkeys to mute/unmute patterns in the Live editor (qseq64)

### ISSUE THREAD

**Issue by unfa** [ahlstromcj/sequencer64#187]
I've just discovered qseq64, and one thing I can't find is using the alphanumeric keyboard to enable/disable patterns in the Live performance mode.

I used to do that in the old seq24 program and it was pretty useful.

Can I map my own hotkeys or use the default "grid" mapping from seq24 that I remember?

**Comment by ahlstromcj** [comment]
By default, qseq64 uses qseq64.rc etc. (There is a command line option to
change this.) You can copy parts from one rc to the other. Also Qt
sometimes requires clicking in order to give keyboard focus to the window.
Let me know if that's not the issue.

**Comment by unfa** [comment]
Thanks! Ok, so in my case running `qseq64 -c sequencer64` used the default configuration that has these keys assigned to toggling sequences.

**Comment by ahlstromcj** [comment]
Hmmm, if you removed the old qseq64.rc and .usr, and rerun qseq64, then exit it, the default hotkeys will appear in the qseq64.rc file, and work.
