### ISSUE TITLE
[feature request] note numbers

### ISSUE THREAD

**Issue by muranyia** [ahlstromcj/sequencer64#19]
I've been wishing for a display of note numbers (#0-#127) in the pattern editor. Is this possible...?

**Comment by ahlstromcj** [comment]
Not sure of the best way to implement this, though it does sound like a good idea.  Write the numbers to the left of the note, inside the note, or to the right of the note?  Put up a tool tip when hovering over the note? Writing the number in blue in the data window (next to the velocity number)?  Will think on this one.

**Comment by muranyia** [comment]
Well I'd like to have them in the pane where we have the note names (C1-C9+) and the piano keys now, and I'd happily exchange the note names for the note numbers (by an option in the Options window). But that's just my use case.
I'd say tool tips "are dead", as they won't work on touch screens.
Thanks for thinking!

**Comment by ahlstromcj** [comment]
Okay, I've got the current-edit highlighting working much better, it took
awhile to figure out how to get it to follow the focus.  You can now
tell easily whether the currently-edited sequence is armed or not, as well.
I also added it to the (new) event editor.

For the note feature, for now I just coded in the ability to toggle it
with a right click in the virtual keyboard area.  I also set it to
draw only every other MIDI note number, as the current font is too
high to fit in every key, and changing fonts actually involves creating a
whole new font bitmap.  Nor do I want to add a couple pixels vertically
at this time.  The seq24 author made his stuff pixel perfect!

Currently, these two upgrades are only in the fixups branch, as I still have
more testing to do on these and other work before I merge it to master to
create 0.9.11..

So, what do you think?  Thanks for the feedback!

**Comment by muranyia** [comment]
Sounds very good. The right-click solution will be perfect.

**Comment by ahlstromcj** [comment]
Okay, version 0.9.11 is now merged into master, with your feature requests,
and a shedload of new features and fixes.  I had broken the queue function!
Enjoy, but let me know of any issues.

-------- muranyia 09:59 Mon 09 May      --------

>Well I'd like to have them in the pane where we have the note names (C1-C9+) and the piano keys now, and I'd happily exchange the note names for the note numbers (by an option in the Options window). But that's just my use case.
>I'd say tool tips "are dead", as they won't work on touch screens.
>Thanks for thinking!
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/19#issuecomment-217923813

-- 
Do something unusual today.  Pay a bill.

**Comment by muranyia** [comment]
Thank You C! With the note numbers, I'm in difficulty... they might not correspond to the actual MIDI note numbers, can you check please?

**Comment by ahlstromcj** [comment]
I am an idiot.  I had the keys numbered backwards, even took a screen shot
of it, and never noticed it.  I stamped a new version, 0.9.12 into master,
tagged as "0.9.12".  It has a couple of minor new features, too.  Thanks for
reporting!  Note that Sequencer24, like Seq24, starts with MIDI note 0 set
as "C-1" (though because of space the bottom C, below C0, is still numbered
as "C1".)

-------- muranyia 06:10 Sun 29 May      --------

>Thank You C! With the note numbers, I'm in difficulty... they might not correspond to the actual MIDI note numbers, can you check please?
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/19#issuecomment-222359843

-- 
Debian Hint #41: You can use 'apt-cache show <package_name>' or 'aptitude show
<package_name>' to get more information about a debian package.

**Comment by arnaud-jacquemin** [comment]
Hello everybody,

This feature is really useful for rhythmic patterns, to sequence drumkv1 for instance! Thank you Chris!

It works as expected and it's even explained in the documentation. Maybe this issue should be closed as fixed?

**Comment by ahlstromcj** [comment]
Yeah, I always forget to close 'em.  Done!  Thanks!
