### ISSUE TITLE
Unable to compile libseq64

### ISSUE THREAD

**Issue by BeatsMe** [ahlstromcj/sequencer64#193]
On Manjaro Linux, I executed following commands and got an error below. 
I don't know if the problem has occurred only on me or not.
I've also reported it to https://aur.archlinux.org/packages/sequencer64-git/ .
Thanks in advance.
```
$ ./bootstrap --full-clean
$ ./bootstrap -ed -rm
$ make
```

```
perform.cpp:5498:1: error: no declaration matches ‘void seq64::perform::clear_seq_edits()’
 5498 | perform::clear_seq_edits ()
      | ^~~~~~~
perform.cpp:5498:1: note: no functions named ‘void seq64::perform::clear_seq_edits()’
In file included from perform.cpp:231:
../include/perform.hpp:254:7: note: ‘class seq64::perform’ defined here
  254 | class perform
      |       ^~~~~~~
make[2]: *** [Makefile:726: perform.lo] Error 1
make[2]: Leaving directory '/home/aki/git/sequencer64/libseq64/src'
make[1]: *** [Makefile:471: all-recursive] Error 1
make[1]: Leaving directory '/home/aki/git/sequencer64/libseq64'
make: *** [Makefile:607: all-recursive] Error 1
[aki@w530 sequencer64]$ uname -a
Linux w530 5.4.13-rt7-MANJARO #1 SMP PREEMPT_RT Mon Jan 20 14:35:54 UTC 2020 x86_64 GNU/Linux
```

**Comment by ahlstromcj** [comment]
I'm not sure how that slop got checked in; usually the stuff at least compiles.  Too high on the Ballmer curve?  (I.e. too much beer?).  Anyway, though I still have things to test, I've merge midi_control to master to create version 0.96.7.  Do a full-clean and rebuild and let me know of any issues.  It's only 7:20AM here, so I have not had any beer.  :-)

**Comment by BeatsMe** [comment]
Good morning from Japan 9pm JST. Thank you for your correction. Now make process has successfully passed. And also arch linux's AUR version has passed through make process and worked fine, though I'm quite new to sequencer64 ;-). Thank you and be careful not to drink too much. Have a nice day.
