### ISSUE TITLE
Loops not playing when using jack

### ISSUE THREAD

**Issue by kerbingamer376** [ahlstromcj/sequencer64#20]
I can start up sequencer64, and make and arm a loop just fine.
My problem is that then I hit play, and nothing plays. My loops are armed, but the playback cursor isn't moving. Any help?

**Comment by ahlstromcj** [comment]
Which branch are you building?
Are you running ALSA or JACK?
If JACK, what are your settings in File / Options / JACK/LASH?
Thanks!

**Comment by kerbingamer376** [comment]
It seems to work fine when not using jack. I'd like to use jack, but the problem starts when I do use it, default jack settings.
Don't know what branch I'm using I used the aur package `sequencer64-git`.

**Comment by ahlstromcj** [comment]
Try the settings in the "Sequencer64 and Yoshimi Tests" / "JACK:" sections
in this file:

   https://github.com/ahlstromcj/sequencer64/blob/master/contrib/notes/jack-testing.txt

You can replace "yoshimi" with your favorite JACK synthesizer.

Note that the "Song Mode" in "JACK/LASH" won't work unless you make a
performance in the Song Editor.

Andother resource is the manual for Sequencer64 at

   https://github.com/ahlstromcj/sequencer64-doc/blob/master/pdf/sequencer64-user-manual.pdf

Now, I did the test using my "new code" branch, called "fixups".  If you can
build that, try it.  But if you don't want to build it, let me know if 
your own test still fails.  I don't have the version that Arch supports
handy, but if you still cannot get it to work, I will check out that code
(version 0.9.9.18) and make sure it works.

Lotta new features in the upcoming 0.9.12, though!  :-)

-------- Martin 09:27 Wed 25 May      --------

>It seems to work fine when not using jack. I'd like to use jack, but the problem starts when I do use it, default jack settings.
>Don't know what branch I'm using I used the aur package `sequencer64-git`.
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/20#issuecomment-221626943

-- 
Debian Hint #13: If you don't like the default options used in a Debian
package, you can download the source and build a version which uses the
options you prefer. See http://www.debian.org/doc/FAQ/ch-pkg_basics.html
(sections 6.13 and 6.14) for more information.

However, bear in mind that most options in most packages can be configured
at runtime, and do not require recompiling the package.

**Comment by ahlstromcj** [comment]
I checked out the 0.9.9.18 build (used by Arch), and it runs with JACK.  Will wait a bit to close the issue though.  Might need to set up an Arch computer sometime :-)

**Comment by Gimmeapill** [comment]
It does - I finally gave it a quick try yesterday and even transport seems to work ok

**Comment by arnaud-jacquemin** [comment]
Hello everybody,

I think I have the same issue if I only check "JACK Transport" in the _Options_ > _JACK/LASH tab_. When I press _Play_, the playback cursor stays stuck, and no note is played. Nothing moves, the window stays still like on this screenshot:
![sequencer64-transport-bug](https://cloud.githubusercontent.com/assets/1387489/17652230/635e08ec-6277-11e6-81e1-d1d29d33f436.png)

If I check "_Transport Master_" or "_Master Conditional_" everything works  as expected.

I use a recent version, compiled straight from the master branch on github : "Sequencer64 0.9.16  2016-07-14 0.9.16-0-g0193728 * master". My OS is KXStudio 14.04.5 with jackd 1.9.11

(English is not my mother tongue, please excuse any errors on my part... I hope I'm clear enough.)

By the way, thank you Chris for your work! It's my first day playing with Sequencer64 and I'm having fun already!

Have a nice day

**Comment by ahlstromcj** [comment]
I think that's a bug inherited from Seq24.  A user named "Stazed" has did a lot of work with the JACK support in his "seq32" project on GitHub, and I've got the code in place, but macroed out, and will eventually try to get it working (there's a lot of code and I've found that JACK synch can be a bit sensitive to small mistakes).

I am also adding a number of other features and bug fixes from Seq32; it's good stuff!

**Comment by arnaud-jacquemin** [comment]
Hello Chris, thanks for you answer.
I confirm that there is a similar issue with seq24 0.9.3, when only "Jack Transport" is checked.
If you need someone to test these changes, I would be happy to help.

**Comment by ahlstromcj** [comment]
Okay, I have checked this issue when configured with --enable-seq32jack and running with the -J flag.  I click JACK Disconnect in File / Options / JACK, then make sure only "JACK Transport" is checked, and the tune plays as it should.  I haven't checked it with seq32jack disabled, but will close this issue anyway.  If you  find the bug when using the original JACK support, please open an issue for "original JACK".  I will rebuild and test that soon, though.
