### ISSUE TITLE
Midi-control-out doesn't send anything after control n°31

### ISSUE THREAD

**Issue by zigmhount** [ahlstromcj/sequencer64#201]
Hi,
My [midi-control-out] section looks as follows (using Akai APC Mini):
```
[midi-control-out]

...

32 1 1     # screenset size, output buss, enabled (1) /disabled (0)

0 [1 0 144 56 1] [1 0 144 56 5] [1 0 144 56 2] [1 0 144 56 3]
...
31 [1 0 144 3 1] [1 0 144 3 5] [1 0 144 3 2] [1 0 144 3 3]

# MIDI Control Out: play
0 [0 144 82 1]

# MIDI Control Out: stop
0 [0 144 82 0]

# MIDI Control Out: pause
0 [0 144 82 0]
...
```

It works fine for the sequence buttons (controls 0 to 31) so I can see the signal coming out of Seq64 in aseqdump and the lights turn on on the controller. However no signal is detected by aseqdump for play/pause/stop.
Is that a mistake in my configuration, or a real bug?

**Comment by ahlstromcj** [comment]
Hmmmm, I will look into it.  Thanks for the report!

-------- zigmhount 07:56 Sat 18 Apr      --------

>Hi,
>My [midi-control-out] section looks as follows (using Akai APC Mini):
>```
>[midi-control-out]
>
>...
>
>32 1 1     # screenset size, output buss, enabled (1) /disabled (0)
>
>0 [1 0 144 56 1] [1 0 144 56 5] [1 0 144 56 2] [1 0 144 56 3]
>...
>31 [1 0 144 3 1] [1 0 144 3 5] [1 0 144 3 2] [1 0 144 3 3]
>
># MIDI Control Out: play
>0 [0 144 82 1]
>
># MIDI Control Out: stop
>0 [0 144 82 0]
>
># MIDI Control Out: pause
>0 [0 144 82 0]
>...
>```
>
>It works fine for the sequence buttons (controls 0 to 31) so I can see the signal coming out of Seq64 in aseqdump and the lights turn on on the controller. However no signal is detected by aseqdump for play/pause/stop.
>Is that a mistake in my configuration, or a real bug?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/201

-- 
Be independent.  Insult a rich relative today.

**Comment by ahlstromcj** [comment]
These control events are laid out in this order: 

    enabled [ channel status d0 d1]

where enabled is 1. Kind of misleading versus other usages of the leftmost value,
I would agree.  So...

   # MIDI Control Out: play
   1 [0 144 82 1]

   # MIDI Control Out: stop
   1 [1 144 83 0]

   # MIDI Control Out: pause
   1 [2 144 84 0]

I've added new code to make the instructions explicit in the generated "rc" file.

Let me know if any related issues crop up!

-------- zigmhount 07:56 Sat 18 Apr      --------

>Hi,
>My [midi-control-out] section looks as follows (using Akai APC Mini):
>```
>[midi-control-out]
>
>...
>
>32 1 1     # screenset size, output buss, enabled (1) /disabled (0)
>
>0 [1 0 144 56 1] [1 0 144 56 5] [1 0 144 56 2] [1 0 144 56 3]
>...
>31 [1 0 144 3 1] [1 0 144 3 5] [1 0 144 3 2] [1 0 144 3 3]
>
># MIDI Control Out: play
>0 [0 144 82 1]
>
># MIDI Control Out: stop
>0 [0 144 82 0]
>
># MIDI Control Out: pause
>0 [0 144 82 0]
>...
>```
>
>It works fine for the sequence buttons (controls 0 to 31) so I can see the signal coming out of Seq64 in aseqdump and the lights turn on on the controller. However no signal is detected by aseqdump for play/pause/stop.
>Is that a mistake in my configuration, or a real bug?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/201

-- 
Has anyone realized that the purpose of the fortune cookie program is to
defuse project tensions?  When did you ever see a cheerful cookie, a
non-cynical, or even an informative cookie?
	Perhaps inadvertently, we have a channel for our aggressions.  This
still begs the question of whether the cookie releases the pressure or only
serves to blunt the warning signs.

	Long live the revolution!
	Have a nice day.

**Comment by zigmhount** [comment]
Yup that works, thanks !
