### ISSUE TITLE
original notes not playing after copy/paste

### ISSUE THREAD

**Issue by 0rel** [ahlstromcj/sequencer64#21]
When notes are copy/pasted with ctrl+c/ctrl+v, the original notes somehow do not play anymore
(Using Arch Linux using RtMidi midi software (executable sound))

After having a quick look into the sources, I think there might be something wrong in sequence::paste_selected(), but this is a wild guess...

**Comment by 0rel** [comment]
After having a second look into that problem, I've found a temporary solution to it. It has to do withe the used multimap datatype where the key/values of the events on the clipboard are modified (timestamps!) and get "out of sync" with their keys, that leave the final merged sequence in a unordered state. - I've added a quick fix to sequence::paste_selected(), but do not think that this will do fix things for every case. - I make a pull request for that.

(Something that came up while trying around is that I could not go back to list based event_lists. Undefining SEQ64_USE_EVENT_MAP got me lots of comiler errors... It would nice if we could keep both -- list and multimap based event lists working...)

Great work by the way! I really liked seq24, and it's great to see alive as sequencer64.

**Comment by ahlstromcj** [comment]
Great!  I've been looking into the verify_and_link() code and could not find any obvious issues.  If I take a sequence with one note, then copy/paste that note, not only does the first note stay on forever, but saving the file continues forever (due to a negative delta-time, so I was able to add a break for that condition).  I will pull your fix and make it official, and also fix your issue with the macro not being defined.   This really isn't the "official" way to do it, but I do all the preliminary work in the "fixups" branch (heh, I misspelled it "fuxips" at first). 

Thanks for kudos (in spite of my bug)!  Also check out the stazed/seq32 project.  He's got some cool code in it, and is bending the JACK handling to his will.

**Comment by ahlstromcj** [comment]
Okay, the copy/paste fix that 0rel provided is also in the "fixups" branch, and has been lightly tested.  I'm inclined to call that fix "good and complete"; even for the largest patterns, it should be fast.  And testing shows that it is not needed for growing or moving events.  Will try more testing to find issues with copy paste, but will also accelerate making the "fixups" branch official as version 0.9.13 in master.

**Comment by ahlstromcj** [comment]
Oh, I also got the application to build and run with the old std::list implementation (i.e. when SEQ64_USE_EVENT_MAP is not defined).

**Comment by ahlstromcj** [comment]
Finally got around to checking for other code that modifies the timestamp of an event in the container in place, which leaves the event key unaltered in the multimap implementation of the event container.  Still have an issue with copy/paste of a whole sequence, so am keeping this issue open.

**Comment by ahlstromcj** [comment]
Man, found some new bugs and some long-standing (seq24) bugs in handle other areas of copy/paste/move in the sequence/pattern editor, thanks to 0rel's work.  We were transposing
(modifying data[0]) of non-note events in a few sequence member functions.  Still working to root out all of the issues.  Thanks, 0rel!

**Comment by 0rel** [comment]
Hey, I'm happy to hear all that! I was great to see seq24/64 from inside for a bit, had quite a debugging session before finding that tiny workaround. ;) I will check the new fixups and the std::list implementation as soon as I'm coming back to working on sound stuff again...

**Comment by ahlstromcj** [comment]
Just merged fixups into master to create 0.9.14, and tagged it as "0.9.14".    In addition to fixes and tweaks, also ported over Stazed's seq32 chord-generation feature and made the song editor page to follow the progress bar.  Enjoy!  Closing this bug for now.
