### ISSUE TITLE
Qt5 build still requires/compiles gtkmm part of seq64

### ISSUE THREAD

**Issue by simonvanderveldt** [ahlstromcj/sequencer64#212]
Not sure if this is still something you'd want to fix and/or how intertwined these things are, but when building using `--enable-qt5` the gtkmm part of sequencer64 is still compiled even though no `seq64` binary is produced.

Excerpt from failed compilation with no gtkmm installed
```
Top source-directory 'top_srcdir' is ..
* * * * * All libseq_rtmidi build items completed * * * * *
make[2]: Leaving directory '/var/tmp/portage/media-sound/sequencer64-0.96.7/work/sequencer64-0.96.7/seq_rtmidi'
make[1]: Leaving directory '/var/tmp/portage/media-sound/sequencer64-0.96.7/work/sequencer64-0.96.7/seq_rtmidi'
Making all in seq_gtkmm2
make[1]: Entering directory '/var/tmp/portage/media-sound/sequencer64-0.96.7/work/sequencer64-0.96.7/seq_gtkmm2'
Making all in include
make[2]: Entering directory '/var/tmp/portage/media-sound/sequencer64-0.96.7/work/sequencer64-0.96.7/seq_gtkmm2/include'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/var/tmp/portage/media-sound/sequencer64-0.96.7/work/sequencer64-0.96.7/seq_gtkmm2/include'
Making all in src
make[2]: Entering directory '/var/tmp/portage/media-sound/sequencer64-0.96.7/work/sequencer64-0.96.7/seq_gtkmm2/src'
make[2]: git: Command not found
/bin/sh: git: command not found
/bin/sh ../../libtool  --tag=CXX   --mode=compile x86_64-pc-linux-gnu-g++ -DLOCALEDIR=\"/usr/share/locale\" -DHAVE_CONFIG_H -I. -I../../include    -I../include -I../../include -I../../libseq64/include -I../../seq_alsamidi/include -I../../seq_portmidi/include -I../../seq_rtmidi/include -I../../resources     -DSEQ64_GIT_VERSION=\"" "\" -O2 -pipe -Wall -Wextra -pedantic -Wno-parentheses  -D_REENTRANT -DAPI_VERSION="0.96"    -O3 -DDEBUG -D_DEBUG -fno-inline    -std=c++14 -Wno-variadic-macros -Wno-deprecated-declarations -c -o eventedit.lo eventedit.cpp
make[2]: git: Command not found
../../libtool: line 85: bcd61a51486c: command not found
/bin/sh: git: command not found
/bin/sh ../../libtool  --tag=CXX   --mode=compile x86_64-pc-linux-gnu-g++ -DLOCALEDIR=\"/usr/share/locale\" -DHAVE_CONFIG_H -I. -I../../include    -I../include -I../../include -I../../libseq64/include -I../../seq_alsamidi/include -I../../seq_portmidi/include -I../../seq_rtmidi/include -I../../resources     -DSEQ64_GIT_VERSION=\"" "\" -O2 -pipe -Wall -Wextra -pedantic -Wno-parentheses  -D_REENTRANT -DAPI_VERSION="0.96"    -O3 -DDEBUG -D_DEBUG -fno-inline    -std=c++14 -Wno-variadic-macros -Wno-deprecated-declarations -c -o eventslots.lo eventslots.cpp
make[2]: git: Command not found
../../libtool: line 85: bcd61a51486c: command not found
/bin/sh: git: command not found
/bin/sh ../../libtool  --tag=CXX   --mode=compile x86_64-pc-linux-gnu-g++ -DLOCALEDIR=\"/usr/share/locale\" -DHAVE_CONFIG_H -I. -I../../include    -I../include -I../../include -I../../libseq64/include -I../../seq_alsamidi/include -I../../seq_portmidi/include -I../../seq_rtmidi/include -I../../resources     -DSEQ64_GIT_VERSION=\"" "\" -O2 -pipe -Wall -Wextra -pedantic -Wno-parentheses  -D_REENTRANT -DAPI_VERSION="0.96"    -O3 -DDEBUG -D_DEBUG -fno-inline    -std=c++14 -Wno-variadic-macros -Wno-deprecated-declarations -c -o font.lo font.cpp
make[2]: git: Command not found
../../libtool: line 85: bcd61a51486c: command not found
/bin/sh: git: command not found
/bin/sh ../../libtool  --tag=CXX   --mode=compile x86_64-pc-linux-gnu-g++ -DLOCALEDIR=\"/usr/share/locale\" -DHAVE_CONFIG_H -I. -I../../include    -I../include -I../../include -I../../libseq64/include -I../../seq_alsamidi/include -I../../seq_portmidi/include -I../../seq_rtmidi/include -I../../resources     -DSEQ64_GIT_VERSION=\"" "\" -O2 -pipe -Wall -Wextra -pedantic -Wno-parentheses  -D_REENTRANT -DAPI_VERSION="0.96"    -O3 -DDEBUG -D_DEBUG -fno-inline    -std=c++14 -Wno-variadic-macros -Wno-deprecated-declarations -c -o fruityperfroll_input.lo fruityperfroll_input.cpp
make[2]: git: Command not found
/bin/sh: git: command not found
../../libtool: line 85: bcd61a51486c: command not found
libtool: compile:  x86_64-pc-linux-gnu-g++ -DLOCALEDIR=\"/usr/share/locale\" -DHAVE_CONFIG_H -I. -I../../include -I../include -I../../include -I../../libseq64/include -I../../seq_alsamidi/include -I../../seq_portmidi/include -I../../seq_rtmidi/include -I../../resources "-DSEQ64_GIT_VERSION=\" \"" -O2 -pipe -Wall -Wextra -pedantic -Wno-parentheses -D_REENTRANT -DAPI_VERSION=0.96 -O3 -DDEBUG -D_DEBUG -fno-inline -std=c++14 -Wno-variadic-macros -Wno-deprecated-declarations -c eventedit.cpp  -fPIC -DPIC -o .libs/eventedit.o
libtool: compile:  x86_64-pc-linux-gnu-g++ -DLOCALEDIR=\"/usr/share/locale\" -DHAVE_CONFIG_H -I. -I../../include -I../include -I../../include -I../../libseq64/include -I../../seq_alsamidi/include -I../../seq_portmidi/include -I../../seq_rtmidi/include -I../../resources "-DSEQ64_GIT_VERSION=\" \"" -O2 -pipe -Wall -Wextra -pedantic -Wno-parentheses -D_REENTRANT -DAPI_VERSION=0.96 -O3 -DDEBUG -D_DEBUG -fno-inline -std=c++14 -Wno-variadic-macros -Wno-deprecated-declarations -c eventslots.cpp  -fPIC -DPIC -o .libs/eventslots.o
eventslots.cpp:45:10: fatal error: gtkmm/adjustment.h: No such file or directory
   45 | #include <gtkmm/adjustment.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:694: eventslots.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
libtool: compile:  x86_64-pc-linux-gnu-g++ -DLOCALEDIR=\"/usr/share/locale\" -DHAVE_CONFIG_H -I. -I../../include -I../include -I../../include -I../../libseq64/include -I../../seq_alsamidi/include -I../../seq_portmidi/include -I../../seq_rtmidi/include -I../../resources "-DSEQ64_GIT_VERSION=\" \"" -O2 -pipe -Wall -Wextra -pedantic -Wno-parentheses -D_REENTRANT -DAPI_VERSION=0.96 -O3 -DDEBUG -D_DEBUG -fno-inline -std=c++14 -Wno-variadic-macros -Wno-deprecated-declarations -c font.cpp  -fPIC -DPIC -o .libs/font.o
libtool: compile:  x86_64-pc-linux-gnu-g++ -DLOCALEDIR=\"/usr/share/locale\" -DHAVE_CONFIG_H -I. -I../../include -I../include -I../../include -I../../libseq64/include -I../../seq_alsamidi/include -I../../seq_portmidi/include -I../../seq_rtmidi/include -I../../resources "-DSEQ64_GIT_VERSION=\" \"" -O2 -pipe -Wall -Wextra -pedantic -Wno-parentheses -D_REENTRANT -DAPI_VERSION=0.96 -O3 -DDEBUG -D_DEBUG -fno-inline -std=c++14 -Wno-variadic-macros -Wno-deprecated-declarations -c fruityperfroll_input.cpp  -fPIC -DPIC -o .libs/fruityperfroll_input.o
In file included from font.cpp:68:
../include/font.hpp:38:10: fatal error: gtkmm/image.h: No such file or directory
   38 | #include <gtkmm/image.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
eventedit.cpp:55:10: fatal error: gtkmm/adjustment.h: No such file or directory
   55 | #include <gtkmm/adjustment.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:694: font.lo] Error 1
fruityperfroll_input.cpp:35:10: fatal error: gtkmm/button.h: No such file or directory
   35 | #include <gtkmm/button.h>
      |          ^~~~~~~~~~~~~~~~
```

**Comment by simonvanderveldt** [comment]
P.S. What's your plan with sequencer64/seq66? Will you still be developing sequencer64 or do you expect you'll focus purely on seq66? In any case, thanks for all the hard work on these awesome tools!

**Comment by ahlstromcj** [comment]
Ugh.  That is annoying enough that I will fix it.  Will have to be careful, as
that automake setup is a bit touchy/krufty.  Thanks for the report!

-------- Simon van der Veldt 07:20 Sun 25 Oct      --------

>Not sure if this is still something you'd want to fix and/or how intertwined these things are, but when building using `--enable-qt5` the gtkmm part of sequencer64 is still compiled even though no `seq64` binary is produced.
>
>Excerpt from failed compilation with no gtkmm installed
>```
>Top source-directory 'top_srcdir' is ..
>* * * * * All libseq_rtmidi build items completed * * * * *
>make[2]: Leaving directory '/var/tmp/portage/media-sound/sequencer64-0.96.7/work/sequencer64-0.96.7/seq_rtmidi'
>make[1]: Leaving directory '/var/tmp/portage/media-sound/sequencer64-0.96.7/work/sequencer64-0.96.7/seq_rtmidi'
>Making all in seq_gtkmm2
>make[1]: Entering directory '/var/tmp/portage/media-sound/sequencer64-0.96.7/work/sequencer64-0.96.7/seq_gtkmm2'
>Making all in include
>make[2]: Entering directory '/var/tmp/portage/media-sound/sequencer64-0.96.7/work/sequencer64-0.96.7/seq_gtkmm2/include'
>make[2]: Nothing to be done for 'all'.
>make[2]: Leaving directory '/var/tmp/portage/media-sound/sequencer64-0.96.7/work/sequencer64-0.96.7/seq_gtkmm2/include'
>Making all in src
>make[2]: Entering directory '/var/tmp/portage/media-sound/sequencer64-0.96.7/work/sequencer64-0.96.7/seq_gtkmm2/src'
>make[2]: git: Command not found
>/bin/sh: git: command not found
>/bin/sh ../../libtool  --tag=CXX   --mode=compile x86_64-pc-linux-gnu-g++ -DLOCALEDIR=\"/usr/share/locale\" -DHAVE_CONFIG_H -I. -I../../include    -I../include -I../../include -I../../libseq64/include -I../../seq_alsamidi/include -I../../seq_portmidi/include -I../../seq_rtmidi/include -I../../resources     -DSEQ64_GIT_VERSION=\"" "\" -O2 -pipe -Wall -Wextra -pedantic -Wno-parentheses  -D_REENTRANT -DAPI_VERSION="0.96"    -O3 -DDEBUG -D_DEBUG -fno-inline    -std=c++14 -Wno-variadic-macros -Wno-deprecated-declarations -c -o eventedit.lo eventedit.cpp
>make[2]: git: Command not found
>../../libtool: line 85: bcd61a51486c: command not found
>/bin/sh: git: command not found
>/bin/sh ../../libtool  --tag=CXX   --mode=compile x86_64-pc-linux-gnu-g++ -DLOCALEDIR=\"/usr/share/locale\" -DHAVE_CONFIG_H -I. -I../../include    -I../include -I../../include -I../../libseq64/include -I../../seq_alsamidi/include -I../../seq_portmidi/include -I../../seq_rtmidi/include -I../../resources     -DSEQ64_GIT_VERSION=\"" "\" -O2 -pipe -Wall -Wextra -pedantic -Wno-parentheses  -D_REENTRANT -DAPI_VERSION="0.96"    -O3 -DDEBUG -D_DEBUG -fno-inline    -std=c++14 -Wno-variadic-macros -Wno-deprecated-declarations -c -o eventslots.lo eventslots.cpp
>make[2]: git: Command not found
>../../libtool: line 85: bcd61a51486c: command not found
>/bin/sh: git: command not found
>/bin/sh ../../libtool  --tag=CXX   --mode=compile x86_64-pc-linux-gnu-g++ -DLOCALEDIR=\"/usr/share/locale\" -DHAVE_CONFIG_H -I. -I../../include    -I../include -I../../include -I../../libseq64/include -I../../seq_alsamidi/include -I../../seq_portmidi/include -I../../seq_rtmidi/include -I../../resources     -DSEQ64_GIT_VERSION=\"" "\" -O2 -pipe -Wall -Wextra -pedantic -Wno-parentheses  -D_REENTRANT -DAPI_VERSION="0.96"    -O3 -DDEBUG -D_DEBUG -fno-inline    -std=c++14 -Wno-variadic-macros -Wno-deprecated-declarations -c -o font.lo font.cpp
>make[2]: git: Command not found
>../../libtool: line 85: bcd61a51486c: command not found
>/bin/sh: git: command not found
>/bin/sh ../../libtool  --tag=CXX   --mode=compile x86_64-pc-linux-gnu-g++ -DLOCALEDIR=\"/usr/share/locale\" -DHAVE_CONFIG_H -I. -I../../include    -I../include -I../../include -I../../libseq64/include -I../../seq_alsamidi/include -I../../seq_portmidi/include -I../../seq_rtmidi/include -I../../resources     -DSEQ64_GIT_VERSION=\"" "\" -O2 -pipe -Wall -Wextra -pedantic -Wno-parentheses  -D_REENTRANT -DAPI_VERSION="0.96"    -O3 -DDEBUG -D_DEBUG -fno-inline    -std=c++14 -Wno-variadic-macros -Wno-deprecated-declarations -c -o fruityperfroll_input.lo fruityperfroll_input.cpp
>make[2]: git: Command not found
>/bin/sh: git: command not found
>../../libtool: line 85: bcd61a51486c: command not found
>libtool: compile:  x86_64-pc-linux-gnu-g++ -DLOCALEDIR=\"/usr/share/locale\" -DHAVE_CONFIG_H -I. -I../../include -I../include -I../../include -I../../libseq64/include -I../../seq_alsamidi/include -I../../seq_portmidi/include -I../../seq_rtmidi/include -I../../resources "-DSEQ64_GIT_VERSION=\" \"" -O2 -pipe -Wall -Wextra -pedantic -Wno-parentheses -D_REENTRANT -DAPI_VERSION=0.96 -O3 -DDEBUG -D_DEBUG -fno-inline -std=c++14 -Wno-variadic-macros -Wno-deprecated-declarations -c eventedit.cpp  -fPIC -DPIC -o .libs/eventedit.o
>libtool: compile:  x86_64-pc-linux-gnu-g++ -DLOCALEDIR=\"/usr/share/locale\" -DHAVE_CONFIG_H -I. -I../../include -I../include -I../../include -I../../libseq64/include -I../../seq_alsamidi/include -I../../seq_portmidi/include -I../../seq_rtmidi/include -I../../resources "-DSEQ64_GIT_VERSION=\" \"" -O2 -pipe -Wall -Wextra -pedantic -Wno-parentheses -D_REENTRANT -DAPI_VERSION=0.96 -O3 -DDEBUG -D_DEBUG -fno-inline -std=c++14 -Wno-variadic-macros -Wno-deprecated-declarations -c eventslots.cpp  -fPIC -DPIC -o .libs/eventslots.o
>eventslots.cpp:45:10: fatal error: gtkmm/adjustment.h: No such file or directory
>   45 | #include <gtkmm/adjustment.h>
>      |          ^~~~~~~~~~~~~~~~~~~~
>compilation terminated.
>make[2]: *** [Makefile:694: eventslots.lo] Error 1
>make[2]: *** Waiting for unfinished jobs....
>libtool: compile:  x86_64-pc-linux-gnu-g++ -DLOCALEDIR=\"/usr/share/locale\" -DHAVE_CONFIG_H -I. -I../../include -I../include -I../../include -I../../libseq64/include -I../../seq_alsamidi/include -I../../seq_portmidi/include -I../../seq_rtmidi/include -I../../resources "-DSEQ64_GIT_VERSION=\" \"" -O2 -pipe -Wall -Wextra -pedantic -Wno-parentheses -D_REENTRANT -DAPI_VERSION=0.96 -O3 -DDEBUG -D_DEBUG -fno-inline -std=c++14 -Wno-variadic-macros -Wno-deprecated-declarations -c font.cpp  -fPIC -DPIC -o .libs/font.o
>libtool: compile:  x86_64-pc-linux-gnu-g++ -DLOCALEDIR=\"/usr/share/locale\" -DHAVE_CONFIG_H -I. -I../../include -I../include -I../../include -I../../libseq64/include -I../../seq_alsamidi/include -I../../seq_portmidi/include -I../../seq_rtmidi/include -I../../resources "-DSEQ64_GIT_VERSION=\" \"" -O2 -pipe -Wall -Wextra -pedantic -Wno-parentheses -D_REENTRANT -DAPI_VERSION=0.96 -O3 -DDEBUG -D_DEBUG -fno-inline -std=c++14 -Wno-variadic-macros -Wno-deprecated-declarations -c fruityperfroll_input.cpp  -fPIC -DPIC -o .libs/fruityperfroll_input.o
>In file included from font.cpp:68:
>../include/font.hpp:38:10: fatal error: gtkmm/image.h: No such file or directory
>   38 | #include <gtkmm/image.h>
>      |          ^~~~~~~~~~~~~~~
>compilation terminated.
>eventedit.cpp:55:10: fatal error: gtkmm/adjustment.h: No such file or directory
>   55 | #include <gtkmm/adjustment.h>
>      |          ^~~~~~~~~~~~~~~~~~~~
>compilation terminated.
>make[2]: *** [Makefile:694: font.lo] Error 1
>fruityperfroll_input.cpp:35:10: fatal error: gtkmm/button.h: No such file or directory
>   35 | #include <gtkmm/button.h>
>      |          ^~~~~~~~~~~~~~~~
>```
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/212

-- 
I'm personally quite happy with one stable release every two years, and
am of the opinion that trying to release more will mean we'll have to
rename the distro from "stable" to "wobbly".
		-- Scott James Remnant on debian-devel

**Comment by ahlstromcj** [comment]
Seq66 is going to get all the new stuff (including the pending Non Session
Manager support).  For Sequencer64, my plan is mostly maintenance and
backporting easy updates to it.  Some of the stuff in Sequencer64 seems now to
be a bit overblown to me (like the grid of sets!)  And the
keystroke/midi-control is just effin' ugly!

However, I always have this fear that the refactoring involved in Seq66 might
cause performance issues.  Another reason to keep it around.  Plus some people
might not like a Qt version.

The seq66 project also includes a seqtool to use for testing (and later for
configuration via a GUI), but it is a low priority and disabled by default.

-------- Simon van der Veldt 07:21 Sun 25 Oct      --------

>P.S. What's your plan with sequencer64 vs seq66? Will you still be developing sequencer64 or do you expect you'll focus purely on seq66? In any case, thanks for all the hard work on these awesome tools!
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/212#issuecomment-716156161

-- 
If your happiness depends on what somebody else does, I guess you do
have a problem.
		-- Richard Bach, "Illusions"

**Comment by simonvanderveldt** [comment]
Sorry, just noticed that this only happens with 0.96.7 and current master works fine. I'll do some more checks, but in the meantime don't look into this, might be a waste of your time otherwise.

**Comment by simonvanderveldt** [comment]
Done with testing, building the Qt5 version without gtkmm actually works fine for 0.96.8 and current master, it didn't with 0.96.7.
I'll go ahead and close this issue, sorry for the noise.
