### ISSUE TITLE
refresh button or update of jack connected devices

### ISSUE THREAD

**Issue by tx0h** [ahlstromcj/sequencer64#214]
hi,

i work with virtual instruments and add them when needed.

actually, sequencer64 doesn't recognized new connected midi sinks, i need to save my work and restart the sequencer to get an updated list. therefor it would be very helpful to have a button to refresh the list of available midi sinks. or a frequently automatic update of the list.

thanks,
tx0h

**Comment by ahlstromcj** [comment]
Unfortunately, sequencer64's current structure doesn't allow for refreshing the
set of connections.  I have a better arrangement, though still not complete, in
place in the seq66 project, which is the future of sequencer64.  In the
meantime, one krufty work-around is to use the --manual-alsa-ports to start
sequencer64, and then use something like qjackctl (JACK) or aconnect (ALSA)
to make the connections.  Sorry for the issue!

-------- tx0h 00:12 Sun 10 Jan      --------

>hi,
>
>#i work with virtual instruments and add them when needed.
>
>actually, sequencer64 doesn't recognized new connected midi sinks, i need to save my work and restart the sequencer to get an updated list. therefor it would be very helpful to have a button to refresh the list of available midi sinks. or a frequently automatic update of the list.
>
>thanks,
>tx0h
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/214

-- 
All things that are, are with more spirit chased than enjoyed.
		-- Shakespeare, "Merchant of Venice"

**Comment by tx0h** [comment]
thank you. also for the work around.
