### ISSUE TITLE
compilation problems

### ISSUE THREAD

**Issue by freddii** [ahlstromcj/sequencer64#218]
./configure --enable-release --enable-rtmidi

checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: error: cannot find input file: `Makefile.in'

**Comment by ahlstromcj** [comment]
Weird.  I can't replicate it here.  I found some other errors relating to
aux-files, though, will fix them soon.

If you don't mind installing a lotta autoconf stuff, you can do the following
commands to recreate all the Makefile.ins and aux-files stuff:

    $ ./bootstrap --full-clean
    $ ./bootstrap -er
    $ make

The bootstrap script creates all the "auto" stuff and then calls ./configure
for you.  Check out the INSTALL file.  Good luck!

-------- freddii 13:38 Wed 27 Jan      --------

>./configure --enable-release --enable-rtmidi
>
>checking whether more special flags are required for pthreads... no
>checking for PTHREAD_PRIO_INHERIT... yes
>checking that generated files are newer than configure... done
>configure: creating ./config.status
>config.status: error: cannot find input file: `Makefile.in'
>
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/218

-- 
It's interesting to think that many quite distinguished people have
bodies similar to yours.

**Comment by freddii** [comment]
Thanks for your response.
This time i got it compiled with same instruction i was doing before from:
https://github.com/ahlstromcj/sequencer64/blob/master/INSTALL
