### ISSUE TITLE
[REQ] add a (GH-compliant) license file

### ISSUE THREAD

**Issue by forart** [ahlstromcj/sequencer64#224]
Hi there, 1st of all thanks for this awesome work !

Since we've 'doxed' it in our [HyMPS project](https://forart.it/HyMPS) (under [AUDIO section](https://github.com/FORARTfe/HyMPS#- ) \ [Sequencers page](https://github.com/FORARTfe/HyMPS/blob/main/Audio/Sequencers.md#-- ) \ [Audio](https://github.com/FORARTfe/HyMPS/blob/main/Audio/Sequencers.md#audio-)), can you please add a GH-compliant license file for it ?

As you know, expliciting licensing terms is extremely important to let anyone better/faster understand how to reuse/adapt/modify sources (and not only) in other open projects and vice-versa.

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://badgen.net/github/license/ahlstromcj/sequencer64)
(badge-generator URL: https://badgen.net/github/license/ahlstromcj/sequencer64)

You can easily set a standardized one through the GH's license wizard tool.

Last but not least, let us know how we could improve - in your opinion - our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Hope that helps/inspires !

**Comment by ahlstromcj** [comment]
Actually Sequencer64 is not really active. It's been far surpassed by my
Seq66 project. I will look into gh licensing for both soon.

**Comment by forart** [comment]
Thanks a lot !

Seq66 just added to the list !

However, to make GH recognize multiple licenses, you have to configure them as done in FLAC or FFMPEG repositories:
https://github.com/xiph/flac
https://github.com/FFmpeg/FFmpeg

Hope that helps !

**Comment by ahlstromcj** [comment]
Does that means simply renaming them to COPYING.FDL etc.?

I'm trying to download a license using "gh license gpl-3.0" (command-line)
but am getting authentication errors even after runnining "gh configure".

**Comment by forart** [comment]
My suggestion is to restart from scratch:
1. delete all license files;
2. recreate each license file, by naming _**LICENSE.<type>**_ (e.g. LICENSE.GPL, LICENSE.LGPL, LICENSE.FDL, etc);
3. Paste licenses texts GH expects inside and be sure to modify only allowed rows (you can also "grab" licenses files from FLAC/FFMPEG and mod only that rows);
4. Check if GH recognize licenses.

Hope that helps.

**Comment by ahlstromcj** [comment]
Thanks! More questions. What is GH then? Is that the badge-gen site? Do I just
drag-and-drop the licenses files on it? All I see is a blank page.

What do you mean by "rows"?

Sorry for these ignorant questions....

**Comment by forart** [comment]
> What is GH then? 
>
Ehmmm **G**it**H**ub...

>Is that the badge-gen site?
>
No, we do use 2 different badge generators services: [Shields.io](https://shields.io/) and [Badgen](https://badgen.net/).

They have specific GitHub dynamic badges.

> Do I just drag-and-drop the licenses files on it? 
>
No, they do need just the repo _user/name_. 
Examples:
![GitHub followers](https://img.shields.io/github/followers/ahlstromcj) = https://img.shields.io/github/followers/ahlstromcj
![GitHub forks](https://img.shields.io/github/forks/ahlstromcj/seq66) = https://img.shields.io/github/forks/ahlstromcj/seq66
![GitHub last-commit](https://badgen.net/github/last-commit//ahlstromcj/seq66) = https://badgen.net/github/last-commit//ahlstromcj/seq66


>All I see is a blank page. What do you mean by "rows"? 
>
You cannot customize the license file text at all, but just some specific rows.
Check out this one, for example: https://github.com/xiph/flac/blob/master/COPYING.FDL

> Sorry for these ignorant questions....
>
Don't worry, we're here to help open source devs !

**Comment by ahlstromcj** [comment]
Well, I got the text from the shields boilerplate site and made 3 LICENSE.*
files from them; they're the same text as in xiph/flac. I committed them
and pushed.

They're in the portfix branch now, and I when I switch to that branch in the
browser I see three links called "LICENSE".

But in xiph/flac, the buttons/links have more descriptive names rather than the
same name for each.

Where did I go wrong?  Thanks!

**Comment by forart** [comment]
...then try to rename files (as said above or like FLAC/FFMPEG repos).

**Comment by ahlstromcj** [comment]
I think I figured out what is needed while using the Insights / Community
Standards / License link to add a LICENSE to Sequencer64.

I will try to change the labels once I merge the branch to "master".

**Comment by MarcoRavich** [comment]
Yes, S64 repo generates the correct license badge now: https://badgen.net/github/license/ahlstromcj/sequencer64
