### ISSUE TITLE
Impossible to unmute patterns when JACK Transport is activated

### ISSUE THREAD

**Issue by arnaud-jacquemin** [ahlstromcj/sequencer64#25]
Hello,

When JACK Transport is activated and playback is on, I am unable to unmute my patterns. Whatever input method I use (mouse, keyboard, MIDI controller), all the patterns stay muted.

If I unmute patterns before launching playback, there are all immediately muted when I click the play button.

I encounter this problem when "_JACK Transport_" is checked in the Options window, with either "_Transport Master_" or "_Master Conditional_" checked. My Jack Start mode is "_Live mode_"

If I uncheck _JACK Transport_ the unmuting works as usual. 

I'm currently using this version: 0.9.17.1  2016-09-09 0.9.17.1-0-g12dc8a3 * master 
compiled today from Github master.

I reverted to this version: Sequencer64 0.9.16  2016-07-14 0.9.16-2-ge49aa2d (e49aa2d5dfda8fd1ac18f188dcac6499b047530c)
and I don't have the issue anymore. Looks like a regression has been introduced sometime between 0.9.16 and 0.9.17.1

Thanks in advance for your help

**Comment by ahlstromcj** [comment]
Thanks.  I'll check it out tomorrow morning.  Got tickets to a local soccer
game tonight. I'm currently importing seq32's song/live mode handling, so
your bug report comes at an auspicious time :-)

**Comment by ahlstromcj** [comment]
Hmmm, I examined the code for issues, then tried to duplicate the issue in the latest fixups branch.  So far, it seems to work for me.  If you're willing, can you "git checkout fixups" and rebuild completely, and let me know if you still have the issue.  I've been moving the "song-mode" flag from the global rc settings into the perform object, so perhaps I fixed the bug accidentally.  Thanks!

**Comment by ahlstromcj** [comment]
I created and tagged version 0.9.17.2.  It seems to work :-)

**Comment by arnaud-jacquemin** [comment]
Hello Chris,
I hope you enjoyed your soccer game!
I've just downloaded version 0.9.17.2 and tested it: I can confirm this problem is solved!
Thank you very much for your quick response and effective fix!
