### ISSUE TITLE
Segmentation Fault on event editing dialog

### ISSUE THREAD

**Issue by alejg** [ahlstromcj/sequencer64#26]
Steps to reproduce:
 - open sequencer64
 - create an empty new pattern and close it
 - right click the new pattern and select Edit events
 - press the ArrowUp key on any text field 
 
GDB Backtrace:
#0  0x00007ffff4bf7df7 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x00007ffff549ff87 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#2  0x0000000000487c82 in seq64::editable_event::format_timestamp[abi:cxx11]() (this=0xa55060) at editable_event.cpp:507
No locales.
#3  0x0000000000487f68 in seq64::editable_event::stock_event_string[abi:cxx11]() (this=0xa55060) at editable_event.cpp:612
        temp = "\320\177\377\377\377\177\000\000\336@E\000\000\000\000\000 \000\000\000\000\000\000\000PP\245\000\000\000\000\000\360\177\377\377\377\177\000\000\a\033J\365\377\177\000\000\005\000\000\000\000\000\000\000\000\360\313~\343Ig\360\300\200\377\377\377\177\000\000\200\200\377\377\377\177\000"
        ts = ""
#4  0x000000000045275f in seq64::eventslots::draw_event (this=0xa54f80, ei=..., index=-1) at eventslots.cpp:846
        yloc = -15
        col = seq64::font::BLACK
        evp = @0xa55060: {<seq64::event> = {_vptr.event = 0xab7b00, m_timestamp = 17179869304, m_status = 4 '\004', m_channel = 0 '\000', m_data = "\000", 
            m_sysex = std::vector of length 1623497637830, capacity -25769803825 = {<error al leer la variable>
        tmp = "  -1-\000\000\000\360`\200\000\000\000\000"
        temp = "  -1-"
#5  0x0000000000453442 in seq64::eventslots::on_move_up (this=0xa54f80) at eventslots.cpp:1274
        old_index = -1
#6  0x00000000004503ff in seq64::eventedit::on_key_press_event (this=0xb53000, ev=0xa90870) at eventedit.cpp:926

**Comment by ahlstromcj** [comment]
Okay, this one was fairly easy, for a change.  (Well, except when users have found the fix for me!)  Fixed in master (v. 0.9.17.3 tagged) and in fixups branch.  Thanks!  Let me know if the fix is complete.

**Comment by alejg** [comment]
Thanks! 
I've tested and it works ok!
