### ISSUE TITLE
Zooming sequencer edit window more than 1:32 kills the program.

### ISSUE THREAD

**Issue by layk** [ahlstromcj/sequencer64#28]
Hi
Zooming sequencer edit window more than 1:32 kills the sequencer giving me 'arithmetic exception'. I think it's a integer divided by zero problem in seqtime.cpp line 217.

I'm using the fixups branch with --enable-debug, #define SEQ64_JACK_SUPPORT and #define SEQ64_STAZED_TRANSPORT

I did a quick fix changing the dividers to float. Diff below and attached.
[diff.txt](https://github.com/ahlstromcj/sequencer64/files/491853/diff.txt)
. 

diff --git a/seq_gtkmm2/src/seqtime.cpp b/seq_gtkmm2/src/seqtime.cpp
index 65ffa39..632dd37 100644
--- a/seq_gtkmm2/src/seqtime.cpp
+++ b/seq_gtkmm2/src/seqtime.cpp
@@ -214,7 +214,7 @@ seqtime::update_pixmap ()
      */
 
     int measure_length_32nds = bpbar * 32 / bwidth;
-    int measures_per_line = (128 / measure_length_32nds) / (32 / m_zoom);
+    int measures_per_line = (int)((128 / (float)measure_length_32nds) / (32 / (float)m_zoom));
     if (measures_per_line <= 0)
         measures_per_line = 1;

**Comment by layk** [comment]
diff attached.
[diff.txt](https://github.com/ahlstromcj/sequencer64/files/491849/diff.txt)

**Comment by ahlstromcj** [comment]
I had fixed a bug with the placement of the END marker using some code from
seq32, and that seems to be what introduced this bug.  Although your fix is
valid, I decided to fix the bug by simplifying the equation and eliminating
the potential for a division by zero.

One minor issue still remains; the maximum zoom needs to be dependent on
the PPQN.  At the default, 192 PPQN, the highest levels of zoom are just
impractical to view in seqedit.  They do help with (for example) 19200 PPQN.

Thanks for the heads up!  It is gratifying to see that people are using
this project.  Be sure to let me know if you see other issues.

Chris

-------- layk 12:29 Sun 25 Sep      --------

>Hi
>Zooming sequencer edit window more than 1:32 kills the sequencer giving me 'arithmetic exception'. I think it's a integer divided by zero problem in seqtime.cpp line 217.
>
>I'm using the fixups branch with --enable-debug, #define SEQ64_JACK_SUPPORT and #define SEQ64_STAZED_TRANSPORT
>
>I did a quick fix changing the dividers to float. Diff below.
>
>diff --git a/seq_gtkmm2/src/seqtime.cpp b/seq_gtkmm2/src/seqtime.cpp
>index 65ffa39..632dd37 100644
>--- a/seq_gtkmm2/src/seqtime.cpp
>+++ b/seq_gtkmm2/src/seqtime.cpp
>@@ -214,7 +214,7 @@ seqtime::update_pixmap ()
>      */
>
>     int measure_length_32nds = bpbar * 32 / bwidth;
>-    int measures_per_line = (128 / measure_length_32nds) / (32 / m_zoom);
>+    int measures_per_line = (int)((128 / (float)measure_length_32nds) / (32 / (float)m_zoom));
>     if (measures_per_line <= 0)
>         measures_per_line = 1;
>
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/28

-- 
Lay on, MacDuff, and curs'd be him who first cries, "Hold, enough!".
		-- Shakespeare

**Comment by ahlstromcj** [comment]
I fixed this around 2016-09-25.  So it should be good in the latest tagged version, 0.9.18.3.
