### ISSUE TITLE
Cannot edit note length

### ISSUE THREAD

**Issue by alejg** [ahlstromcj/sequencer64#29]
When the note length is longer than the measure the editor behaves incorrectly, not allowing to change the note off position.

![seq64](https://cloud.githubusercontent.com/assets/15330205/18820832/4973aac4-8377-11e6-8a01-4ee1a11214bd.png)

The note length editing feature works fine in seq24.

**Comment by ahlstromcj** [comment]
That behavior of seq24 (and seq32) actually seems like a misfeature to me.  A note that wraps around at the END marker?  But, since those two project support it, I'll go ahead a look into fixing it, or making it the default option for too-long or would-wrap notes.  Thanks!

**Comment by ahlstromcj** [comment]
If you have a chance, can you try the latest fixups commit?  I fixed one little thing (changed a ">" to ">=") and I tried a couple of note length changes in seq24, seq32, and sequencer64, and they all behaved the same.  What I did was take a note and stretch it beyond the measure.  Then I selected the note again and shrunk it (but leaving it still wrapped around), and the wrap-around shrunk.

But if you find a specific situation that messes up, please let me know.  Thanks, man!

**Comment by alejg** [comment]
Thanks!
I've tried and now it's working!.
A strange behaviour appears when I CTRL + Arrow left or right over a note,
an outline is being drawn and do not disappears until you do a click on the
background. Anyway Im able to do what I want :)



2016-09-26 19:50 GMT-03:00 C. Ahlstrom <notifications@github.com>:

**Comment by ahlstromcj** [comment]
Okay, finally tried it and I see what you mean.  I will look into it tonight or tomorrow.
Meantime, check out the latest fixups branch!

**Comment by ahlstromcj** [comment]
I also found a really bad bug in the perfedit/perfroll pattern painting.  So bad I'm surprised I haven't heard a report on it.  It was operating on the previously-selected pattern, not the one currently selected.  Fixed now, so definitely need the latest fixups branch.  In fact, the bug exists in v. 0.9.17, so version 0.9.18 will be out in master in a little while.
