### ISSUE TITLE
Unable to write the BPM

### ISSUE THREAD

**Issue by alejg** [ahlstromcj/sequencer64#30]
The BPM spin box shows that is allowed to write on it, but when try to enter numbers, the pattern toggle shortcuts are triggered.

**Comment by ahlstromcj** [comment]
Yeah, that's a bug since the very beginning (seq24).  I'll see if I can get that control to have sole keyboard focus if you click into it.  Another option (ugly) is a little popup window.  There's a similar bug in the File / Options / Keyboard page :-)

**Comment by alejg** [comment]
thanks! meanwhile you can simply make look as read only (grayed out), also a TAP button feature (with it's corresponding keyboard shortcut) would be nice.

**Comment by ahlstromcj** [comment]
What's a TAP button do?

**Comment by alejg** [comment]
sorry about my english, tap tempo button, like many sequencers, delays and DAWs have.

**Comment by ahlstromcj** [comment]
I think I fixed the BPM issue.  The Name and Set fields also had the issue.   However, to fix the Set field so you could edit it, I had to disable wrap-around.  Seems okay, since it's fairly fast to scroll only 32 steps.  Let me know what you think!  Check the latest commit from fixups (fc95a0d30).  Also thinking about the tap button.

**Comment by ahlstromcj** [comment]
In the latest commit in the fixups branch, there is a Tap button (it has a 0 in it, hover for a tooltip).
As you tap it, it updates the BPM number.  Currently mapped to F9 as well.  Configurable, there is
a new "Ext Keys" page in the Options dialog.  However, I just finished it and it hasn't had any
testing yet.

Have fun!

**Comment by alejg** [comment]
Thanks!, works fine from master branch!
