### ISSUE TITLE
Strange behavior of the mute button in live mode

### ISSUE THREAD

**Issue by AndrewPy** [ahlstromcj/sequencer64#37]
When playing is stopped, the mute button toggles the mute status of the tracks. That's ok.

But while playing, the first press on the mute button mutes *all* tracks (and activates the empty ones). And the next press on the mute button activates all tracks (and mutes the empty ones).

**Comment by ahlstromcj** [comment]
Thanks, I'll look into that.  I assume you think the mute button should work just like it does when playing is stopped.  Let me know if that's not the case.

**Comment by AndrewPy** [comment]
Thank you, yes it would be clearer if it is the same as when the playing is stopped. At least the previous state should be restored in the case of un-mute.

As it is now, one also can not recognize (in "play mode") whether it is muted or not .

**Comment by ahlstromcj** [comment]
I have a question.  The build can enable a better toggling of playing by defining SEQ64_TOGGLE_PLAYING in perform.hpp.  Right now, though, this feature is independent of Song mode, and works best with Live mode.  In Song mode, you can now mute and unmute the playing tracks.  But this interacts with the triggers layed out in the Song editor.  One idea is, at every trigger change, to copy the status into the saved armed array.  Another idea is simply to disable the Mute toggle button when Song mode is active.

Just thinking.  Let me know what you're thinking.  The feature is pretty nice in Live mode, but one can
unmute other tracks in that mode, and they won't be included in the saved armed status until the next time the Mute button is activated.

**Comment by AndrewPy** [comment]
Thanks, the mute function in live mode looks perfect now.

But the mute function in song mode is confusing. Here I would suggest to disable the mute toggle button completely.

By the way: In the file seq_gtkmm2/src/eventedit.cpp the description in the comments is wrong. (Looks like it was copied from perfedit.cpp.)
