### ISSUE TITLE
No "play cursor" in empty piano roll

### ISSUE THREAD

**Issue by AndrewPy** [ahlstromcj/sequencer64#39]
No "play cursor" is displayed in the piano roll of an empty track, but it would be very useful for recording. (The cursor is visible after the first note has been recorded.)

**Comment by ahlstromcj** [comment]
Sounds like a side-effect of not bothering with a cursor in empty slots in the main window, and is a reasonable request.  Will check it out.  Thanks!

**Comment by ahlstromcj** [comment]
I fixed this in the latest "fixups" commit.  Let me know if you think it does what you want.  The fix was pretty simple.

**Comment by AndrewPy** [comment]
Now it works perfectly. Thank you!
