### ISSUE TITLE
cut and paste in sequence editor does not work.

### ISSUE THREAD

**Issue by layk** [ahlstromcj/sequencer64#40]
Hi
Cut and paste in sequence editor does not work on master or fixups branches. I'm using fixups with --enable-debug and #define SEQ64_STAZED_JACK_SUPPORT.

It seems that doing the cut from cut_selected() makes a recall to copy_selected() thus clearing the clipboard with m_events_clipboard.clear();

The following change in sequence.cpp in function sequence::copy_selected () works for me.

`diff --git a/libseq64/src/sequence.cpp b/libseq64/src/sequence.cpp
index 91bfcad..5cf60fb 100644
--- a/libseq64/src/sequence.cpp
+++ b/libseq64/src/sequence.cpp
@@ -2151,6 +2151,7 @@ sequence::copy_selected ()
     }
     if (! clipbd.empty())                           /* (clipbd.count() > 0) */
     {
+        m_events_clipboard.clear();
         midipulse first_tick = DREF(clipbd.begin()).get_timestamp();
         if (first_tick >= 0)
         {
@@ -2163,8 +2164,6 @@ sequence::copy_selected ()
         }
         m_events_clipboard = clipbd;
     }
-    else
-        m_events_clipboard.clear();
 }
 
 /**
`

[diff.txt](https://github.com/ahlstromcj/sequencer64/files/517994/diff.txt)
Diff against fixups attached.

**Comment by ahlstromcj** [comment]
I will likely include your change, as it is better C++.

However, building with --enable-debug, --disable-shared, and --enable-seq32jack from the latest
fixups code doesn't show the problem for me.    I think it would be informative if you could lists
the steps that didn't work.  I can encircle a bunch of notes, hit Ctrl-C, and then Ctrl-V them via
keyboard or mouse.  

Anyway, I will look at your diff.txt in about 2 seconds :-)

**Comment by layk** [comment]
Hi 
The cut ctrl-x and then trying to ctrl-v pastes nothing since the m_events_clipboard is empty. ctrl-c and then pasting works ok since it does not go through cut_selected() function.

I will try to build as you informed. Do i still have to do the bootstrap with --enable-debug?

**Comment by ahlstromcj** [comment]
Okay, tried it.  I did not add the m_events_clipboard.clear() statement, because the later
m_events_clipboard = clipbd statement should do that anyway (unless there's some bug in
event_list::operator =).

I did comment out the "else m_events_clipboard.erase()" statement, and cut-n-paste still works
for me.  I will try to figure out exactly can happen.  So far I can't seem to break copy/paste with
either the old or new (your diff) code.

Thanks!

**Comment by layk** [comment]
I just compiled master branch with ./bootstrap and the mentioned flags and cut/paste does not work.

**Comment by ahlstromcj** [comment]
I was able to duplicate it after all,  *CUT*, not *COPY*!  Doh!  Anyway, your fix works and I will commit it soon to fixups.  I will spend a little more time to follow up on it some more, and then make yet another bugfix release, 0.9.18.3.  Thanks for finding (and fixing) this nasty bug!

**Comment by ahlstromcj** [comment]
By the way, "./bootstrap -ed" ("-ed" is short for "--enable-debug") just adds a call to ./configure --enable-debug --disable-shared.  But if I want extra options beyond those, I just do "./bootstrap" and then
run ./configure with all the options I need.

**Comment by ahlstromcj** [comment]
Oh, one more thing.  I should warn you that the STAZED JACK SUPPORT (--enable-seq32jack) is still in progress.  The code is all there, but needs some heavy testing.

**Comment by layk** [comment]
Yes i got it now. Doing only ./bootstrap gives the instructions.
Most excellent project btw. I'm glad that someone is doing this. I've been using seq24 as the heart of my setup for years. And the documentation is outstanding.
I try to help/debug where i can.

**Comment by ahlstromcj** [comment]
This one was fixed around 2016-10-08, and resulted in 0.9.18.3.
