### ISSUE TITLE
Recording midi note is fixed length due to missing handling of is_pattern_playing(bool) in perform.cpp

### ISSUE THREAD

**Issue by layk** [ahlstromcj/sequencer64#42]
Hi
Trying to record midi notes all notes are recorded in fixed length due to is_pattern_playing() is always false in sequence::stream_event (event & ev) in perform.cpp line 2841 thus going to step-edit feature in that same function.

As a side note setting this boolean value was done in mainwind.cpp in seq24 0.9.3 

To me the most logical place to set the flag for given functionality (toggle between live record and step-edit) seems to be in perform::playback_key_event (const keystroke & k, bool songmode) in perform.cpp since all possibilities are in that function (pause/play/stop). I added is_pattern_playing(bool); for all the possibilities.

With this attached patch is_pattern_playing is set and note length is now recorded.

BTW there was one declaration in perform.cpp line 2048 with a comment 'Hmmmmm'.
    is_pattern_playing(false);              // hmmmmmmmmmmmmmmmmmm

I'm using fixups with --enable-debug --disable-shared --enable-seq32jack

Patch attached below.

[diff_fix.txt](https://github.com/ahlstromcj/sequencer64/files/520552/diff_fix.txt)

>iff --git a/libseq64/src/perform.cpp b/libseq64/src/perform.cpp
>index ca50735..48b110b 100644
>--- a/libseq64/src/perform.cpp
>+++ b/libseq64/src/perform.cpp
>@@ -4021,16 +4021,26 @@ perform::playback_key_event (const keystroke & k, bool >songmode)
>             if (onekey)
>             {
>                 if (is_running())
>+                {
>                     pause_playing(songmode);
>+                    is_pattern_playing(false);
>+                }
>                 else
>+                {
>                     start_playing(songmode);
>+                    is_pattern_playing(true);
>+                }
>             }
>             else if (! is_running())
>+            {
>                 start_playing(songmode);
>+                is_pattern_playing(true);
>+            }
>         }
>         else if (k.key() == keys().stop())
>         {
>             stop_playing();
>+            is_pattern_playing(false);
>         }
> #ifdef SEQ64_PAUSE_SUPPORT
>         else if (k.key() == PAUSEKEY)

**Comment by ahlstromcj** [comment]
Thanks!  I incorporated your fix, with minor changes.  But am looking to see if the fix should be in the pause_playing() and start/stop_playing() functions instead.  The mainwnd and perfedit modules call them directly.  However, it may be better to just get them to call perform::playback_key_event() instead.
I am very glad you are testing the Seq32 (Stazed's) JACK code; I have tweaked it a hair in the latest fixups, so let me know of any issues.  Great work!!

**Comment by layk** [comment]
Alright. Btw i noticed that either opening or importing midi file opens up two similar sequences at least with the midi files i used. I might take a look at that next.

**Comment by ahlstromcj** [comment]
The main difference between open and import is that the latter (1) doesn't
necessarily delete data already there; and (2) let's you choose what Set to
put the tracks in.

On Oct 11, 2016 8:41 AM, "layk" <notifications@github.com> wrote:

Alright. Btw i noticed that either opening or importing midi file opens up
two similar sequences at least with the midi files i used. I might take a
look at that next.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ahlstromcj/sequencer64/issues/42#issuecomment-252905420>,
or mute the thread

**Comment by ahlstromcj** [comment]
This issue was fixed around 2016-10-11.  Will await layk's follow-on issue in a separate GitHub issue entry.
