### ISSUE TITLE
Upper case midi file extension filtering when opening file

### ISSUE THREAD

**Issue by layk** [ahlstromcj/sequencer64#43]
Hi

I downloaded some midi files the other day with uppercase midi file extensions(*.MID) and did not see those when opening in sequencer64 with default filter 'MIDI Files' but only with 'Any Files'.

I added upper case filters in mainwnd.cpp mainwnd::choose_file () function.

Patch attached
[diff.txt](https://github.com/ahlstromcj/sequencer64/files/521098/diff.txt)

**Comment by ahlstromcj** [comment]
Added!  See latest fixups commit.  Thanks again!

**Comment by ahlstromcj** [comment]
Fixed around 2016-10-11.
