### ISSUE TITLE
Undo(ctrl-z) removes two instanses of history via seqedit::on_key_press_event (GdkEventKey * ev)

### ISSUE THREAD

**Issue by layk** [ahlstromcj/sequencer64#46]
Hi
Undoing(ctrl-z) removes two instances of history.To reproduce this if one makes three notes one at a time and presses ctrl-z once only the first one remains. Same goes for moving notes.

This is due to a else-if statement in seqedit.cpp line 2544 where m_seqroll_wid->on_key_press_event(ev) calls seqroll::on_key_press_event making first removal. This if statement is never true and seqroll::on_key_press_event is called again on line result = Gtk::Window::on_key_press_event making another m_seq.pop_undo(); in seqroll.cpp.

There was also a friend class definition in seqroll.hpp stating:
    /**
     *  For accessing on_key_press_event().  It would be good to be able to
     *  avoid this access!
     */
    friend class seqedit;

I'm not quite sure what was the notion here with friend class and all but changing this else-if to if (ev->keyval == 'z') seems to work for me in sequence editor. It also seems to me that regarding this undo problem there is no need for friend class declaration anymore.

Patch attached for testing and thoughts.
Edit: New version:
[diff.txt](https://github.com/ahlstromcj/sequencer64/files/534914/diff.txt)

**Comment by ahlstromcj** [comment]
Thanks! Will check it out after supper. Your reports are *greatly*
appreciated!

**Comment by layk** [comment]
Ok. Btw i just did a quick tests. And i will send a working patch. That one errors.

**Comment by layk** [comment]
There is a working version now on fist comment.

**Comment by layk** [comment]
And 'z' should be SEQ64_Undo. else if (ev->keyval == SEQ64_Undo)
Patch attached.
[diff2.txt](https://github.com/ahlstromcj/sequencer64/files/535100/diff2.txt)

**Comment by layk** [comment]
Or maybe it should be omitted  altogether. IT works that way also. Result is false.

**Comment by ahlstromcj** [comment]
There was actually more to the story, as we need to allow z and Z in the text-entry fields.  See the latest commit.  Your SEQ64_Undo fix may still be useful, but I have to  got to my real job soon, and don't have time to try it.  Anyway, I had to make sure that z, 0, and Z were not being applied to the pattern-name field before allowing them to be used for zoom in the seqroll.  Getting a little to tricky :-(.  Let me know what your further testing reveals.  Thanks!

**Comment by layk** [comment]
Everything seems to be working well with your commit. I went through all the possibilities in the function(moving, zooming , w and z). The undo works good for me. 
Also tried changing to (ev->keyval == SEQ64_Undo) and it works also so it does not matter.

I would say that all is good here for now.

I try to look at the midi file import issues next as i mentioned earlier. Depending on the midi file use i get double imports both having same sequence or double imports with one empty and and so on depending on the midi file used.

**Comment by ahlstromcj** [comment]
Actually, I completely removed the undo from seqedit now, as it is already implemented, along with redo, in seqroll.  Saves a little code.  Should have thought of it earlier.

If you find certain files are imported in a crazy way, be sure to attach them to that issue.  Thanks!

**Comment by layk** [comment]
Ok. And Ill attach the missbehaving midi files.

**Comment by ahlstromcj** [comment]
Fixed around 2016-10-18.  Will be official (as will be other recent issues) in upcoming version 0.9.19, but can currently be found in the fixups branch.
