### ISSUE TITLE
No save file dialog on exit if only a midi port or channel has been changed

### ISSUE THREAD

**Issue by AndrewPy** [ahlstromcj/sequencer64#47]
When terminating the program, there is no save file dialog if only a midi-port or channel has been changed.

**Comment by ahlstromcj** [comment]
Checking it out right now.  Hopefully pretty straightforward.

**Comment by ahlstromcj** [comment]
It should be fixed now, in the latest commit in fixups branch.  However, there is no undo/redo support for this kind of change (undo/redo apply to MIDI events only).

**Comment by AndrewPy** [comment]
Perfect, thank you.
