### ISSUE TITLE
Mute Groups should be applied to active screen

### ISSUE THREAD

**Issue by TDeagan** [ahlstromcj/sequencer64#5]
Currently Mute Groups are applied to Screen 0 only.  

This was what was intended to be fixed by Pull Request https://github.com/ahlstromcj/sequencer64/pull/3 , but additional vars in the code where the active screen is not being tracked have been identified.  I'll reference this issue when I create a new pull request with a candidate solution.

**Comment by arnaud-jacquemin** [comment]
Hello Tim,

I'm using a recent version of Sequencer64 (0.9.16, dated 14/07/2016), and mute groups seems to be  applied to the currently displayed screen. Have you been successful fixing this issue ?

Thanks in advance

**Comment by ahlstromcj** [comment]
After some testing recently, I think this issue can be closed.  It seems to act like seq24.  Am also beefing up and clarifying the documentation in the sequencer64-doc project.
