### ISSUE TITLE
Double clicking track vs hi-freq mute-unmute clicking

### ISSUE THREAD

**Issue by muranyia** [ahlstromcj/sequencer64#51]
The way use the program involves frequent clicking on individual tracks to mute/unmute them. With the new double click trigger I cannot click one too frequently any more otherwise it will be detected as a double click and the track will be opened for editing.
Any chance to make this optional?

**Comment by ahlstromcj** [comment]
That sounds like a good idea!  Will likely do that today.  May also add a "double-click" interval setting, if practical.  Thanks for these reports that help the app get better!

**Comment by ahlstromcj** [comment]
Added in the latest commit to the "fixups" branch, will eventually be in 0.9.20.  I did not add a double-click interval setting.  Also, be aware that --enable-seq32jack is now the default.  If you don't like it, then reconfigure with --disable-seq32jack and rebuild, and let me know what is wrong.  Thanks!

**Comment by muranyia** [comment]
Somehow missed this - it works and it's very convenient. Thank You.
