### ISSUE TITLE
bootstrap mentions 'enable-seq43jack'

### ISSUE THREAD

**Issue by muranyia** [ahlstromcj/sequencer64#55]
When the bootstrap script is finished it displays
`Note that --enable-seq43jack is now the default!`

**Comment by ahlstromcj** [comment]
Thanks for the report!  I'm a bit tied up right now, working in the "rtmidi" branch.  I got PortMIDI working under Linux, and am now trying to reimplement the ALSA interface using a really warped version of RtMidi, and once that works, then add native JACK support.

**Comment by ahlstromcj** [comment]
Did this awhile back!  Thanks!
