### ISSUE TITLE
Jack MIDI Client Naming

### ISSUE THREAD

**Issue by georgkrause** [ahlstromcj/sequencer64#61]
There is an issue with the naming of clients when using the a2jmidid bridge.

eg the Midi Through port is named "(pl Midi Through Port-0"
or the amsynth midi in port is simply called "MIDI IN" which is obviosly not that useful ;)

i could do some more testing with some other alsa midi devices tomorrow.

**Comment by ahlstromcj** [comment]
So I started up qjackctl and "a2jmidid --export-hw".  Running
"seq64 -A -a" (ALSA) was fine, but "seq64 -t" showed the issue.
I will rebuild with debug into and extra debug output and see
how this can be happening.

Thanks for the report!  As for amsynth, I've noticed some apps
might not expose the client name, just the port name.

I assume you need a2jmidid for other ALSA MIDI applications, now.

-------- Georg Krause 14:34 Wed 22 Feb      --------

>There is an issue with the naming of clients when using the a2jmidid bridge.
>
>eg the Midi Through port is named "(pl Midi Through Port-0"
>or the amsynth midi in port is simply called "MIDI IN" which is obviosly not that useful ;)
>
>i could do some more testing with some other alsa midi devices tomorrow.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/61

-- 
Q:	What's buried in Grant's tomb?
A:	A corpse.

**Comment by ahlstromcj** [comment]
So debugging shows seq64 is getting different names from jack_get_ports() when a2jmidid is running.
I see in qjackctl that a2jmidid appends " (playback)" or " (capture)" to the client name.  Obviously the parsing that seq64 does is getting confused by that.  Hopefully a straightforward fix, though I won't get to it until tonight (gotta work all day :-( ha!).

**Comment by ahlstromcj** [comment]
I think I have fixed the issue.  Please checkout the "wip" (work-in-progress) branch and let me know of any remaining issues when a2jmidid is running.  Why did they leave the ":" in the port name!!!?

**Comment by georgkrause** [comment]
fixed
