### ISSUE TITLE
Jack Midi auto connect

### ISSUE THREAD

**Issue by georgkrause** [ahlstromcj/sequencer64#62]
should all the jack midi busses be auto connected to their clients right now? in my case, the system midi_playback_1 is automatically connected, all the others aren't. is this expected behavior? i really like the idea of auto connecting busses ;)

**Comment by ahlstromcj** [comment]
I suspect the naming issue you found with a2jmidid is interfering with
connecting, as the JACK connections are made using the client:port name.

Also, if you don't want auto-connect, you can use the -m option
(--manual-alsa-ports, which I will rename --manual-ports or --virtual-ports
later) and make the connections yourself.

-------- Georg Krause 14:36 Wed 22 Feb      --------

>should all the jack midi busses be auto connected to their clients right now? in my case, the system midi_playback_1 is automatically connected, all the others aren't. is this expected behavior? i really like the idea of auto connecting busses ;)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/62

-- 
Even the clearest and most perfect circumstantial evidence is likely to be at
fault, after all, and therefore ought to be received with great caution.  Take
the case of any pencil, sharpened by any woman; if you have witnesses, you will
find she did it with a knife; but if you take simply the aspect of the pencil,
you will say that she did it with her teeth.
		-- Mark Twain, "Pudd'nhead Wilson's Calendar"

**Comment by ahlstromcj** [comment]
I think I have fixed the issue.  Please checkout the "wip" (work-in-progress) branch and let me know of any remaining issues when a2jmidid is running.  Why did they leave the ":" in the port name!!!?  It separates the client and port names ("client:port").

**Comment by georgkrause** [comment]
i would say this works.
