### ISSUE TITLE
[Feature request] tempo to two decimal places

### ISSUE THREAD

**Issue by milkmiruku** [ahlstromcj/sequencer64#63]
Being able to set the tempo to two decimal places would be very handy for beatmatching and mixing with an audio source, either live or recorded.

**Comment by ahlstromcj** [comment]
I will start looking into this in a few days, along with stripping out any remaining GUI dependencies.

**Comment by ahlstromcj** [comment]
I went through all the usage of BPM and basically converted it from int to double (typedef "midibpm").  It seems to work.

To activate it, first back up your old sequencer64.usr file for safe-keeping.  Then run sequencer64 or seq64 (whichever one you like to build) from the command line with the --user-save option.  Then exit the application, and compare the backed-up file with the new file to make sure nothing got fubared.  You can then edit the sequencer64.usr file to change the digits of precision (0, 1, or 2) and the step and page increment of the BPM.

Lemme know if it works for you!

**Comment by milkmiruku** [comment]
Awesome! Seems to work fine. Might it be possible to have a second MIDI control for fine BPM alteration?

**Comment by ahlstromcj** [comment]
Actually, I have added BPM "page up" and "page down" MIDI controls as well.  I noticed that, if the BPM field has input focus, the Up and Down arrow keys change BPM by a "step" size, while the Page Up and Page Down keys change BPM by a larger "page" size.  The "step" size and "page" size are configurable in the "usr" file as noted above.  So you could use the existing step BPM increment as a fine control, and the new page BPM increment as a coarse control.  Haven't yet tested the latter as a MIDI control.  

Check out the PDF in the "cja" branch of the "sequencer64-doc" project for documentation of the new BPM and MIDI control items.  Currently testing and thinking.

**Comment by milkmiruku** [comment]
A-ha, thank ya! Now got BPM page and step control bound to the two jog wheels on a DJ controller, just right for dialling in a speed.

**Comment by ahlstromcj** [comment]
Just this minute I checked a working version of the "coarse" ("page") BPM
MIDI control, as well as adding an example to sequencer64-doc.

Let me know if any other improvements occur to you.  Thanks!

-------- Milk Brewster 08:18 Sun 26 Mar      --------

>A-ha, thank ya! Now got BPM page and step control bound to the two jog wheels on a DJ controller, just right for dialling in a speed.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/63#issuecomment-289290890

-- 
Debian Hint #24: If you would like to thank a maintainer for handling an
issue, check out reportbug --kudos.

**Comment by milkmiruku** [comment]
A-ha; FWIW, both forms of BPM MIDI controls seemed to be working (whilst not playing) with the previous build, though I guess there were code improvements to be made. Thanks again :)

**Comment by ahlstromcj** [comment]
Odd.  I was finding under the debugger that the BPM page control was
activating, say the page increment, and then immediately the page decrement.
So we break out of the loop when handling an "extended" MIDI control.
Probably a side-effect of the note off after the note on in my example setup, but I didn't figure out how it was happening.  A minor mystery remains.  :-(

-------- Milk Brewster 01:41 Mon 27 Mar      --------

>A-ha; FWIW, both forms of BPM MIDI controls seemed to be working (whilst not playing) with the previous build, though I guess there were code improvements to be made. Thanks again :)
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/63#issuecomment-289390109

-- 
Q:	How can you tell when a Burroughs salesman is lying?
A:	When his lips move.

**Comment by ahlstromcj** [comment]
This seems to work, it's actually been in for more than a month, and is in master since 0.90.1.
