### ISSUE TITLE
no midiclock output on rtmidi 0.90.1

### ISSUE THREAD

**Issue by F0rth** [ahlstromcj/sequencer64#67]
Hi, 

I've tried 0.90.1 seq64 (rtmidi) and lastest commit from wip branch but can't get midi clock output on both.
Is it a known bug or do you need debug files to help ?

regards,

F.

**Comment by ahlstromcj** [comment]
Will need debug files.   Will have to test against legacy (sequencer64) so
that I see what should be happening.   Thanks!

**Comment by ahlstromcj** [comment]
Well, apparently I forgot to finish midi_jack::api_clock().  I will rectify
that omission ASAP, hopefully by Wednesday.   I am an idiot.

**Comment by F0rth** [comment]
thanks! I rebuilt seq64 with --enable-debug but didn't find the next step to have a debug output.
Super cool you found the root cause.

**Comment by ahlstromcj** [comment]
It seems to happen in ALSA too.  Might be settings there;  seq24 seems to
work though.

**Comment by ahlstromcj** [comment]
Well, I found I had disabled the MIDI clock in the alsamidi build and the rtmidi build by defining an overload for clock() that was being called instead of the proper function.  I think it works, but don't have time to test right now.  If you can pull the latest wip, build it, and see if it improves the issue, that would help a lot.  Thanks!

**Comment by F0rth** [comment]
@ahlstromcj I've build the latest wip and seq64 (rtmidi) sends midi clock messages but lacks midi start and stop ones, whereas alsa version don't.

**Comment by ahlstromcj** [comment]
Cool. Progress!

**Comment by ahlstromcj** [comment]
I found a few more events not yet implemented.  You can try the latest in wip.  However, I need to study a little bit more to make sure I understand all the nuances of these events, and I have to figure out a good way to test this on my rather minimalistic setup (mostly just a laptop and a Korg nanoKEY2).  So there will probably be a few more changes coming.  Plus I'm still figuring out how to add a real "solo" control for another issue.

**Comment by F0rth** [comment]
I've tested the last wip commit and midi start/stop work for my hardware setup. Thanks! . I did the test with midi snoop and a sonic potion lxr.

**Comment by ahlstromcj** [comment]
I'll consider this one closed now :-)
