### ISSUE TITLE
XRUNS with latest wip or master branch

### ISSUE THREAD

**Issue by layk** [ahlstromcj/sequencer64#68]
Hi

I'm getting lot's of XRUNs with low latency settings on jack using either latest master or wip branch with debug enabled. I compiled with (-ed -rm) seq64 and (-ed -am) sequencer64.

I'm using RT kernel on my fresh fedora 25 system 4.9.11-200.rt9.1.fc25.ccrma.x86_64+rt.
Audio card is snd_ice_1712 based.
My jack settings were 48000/128/2(5.33 ms) and 48000/64/3(4 ms).
Same settings work well with seq24, hydrogen and one zynaddsubfx with two sequences from seq24. A clip fom my 33 minute test run with seq24: https://www.youtube.com/watch?v=E8nIcg6qmHw

Log from console:
 ./seq64 
[Reading rc configuration /home/.config/sequencer64/sequencer64.rc]
[Reading user configuration /home/.config/sequencer64/sequencer64.usr]
Non-I/O port 'Axiom 61'
Cannot lock down 107335194 byte memory area (Cannot allocate memory)
[JACK server already started]
[JACK client:uuid is seq64_transport:10]
[JACK sync master]
Cannot use real-time scheduling (RR/55)(1: Operation not permitted)
JackClient::AcquireSelfRealTime error
[JACK sync enabled]
[JACK sync still enabled]
[JACK sync still enabled]

This is the log from qjackctl:
17:08:12.003 XRUN callback (60).
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
17:08:18.992 XRUN callback (61).
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
17:08:48.068 XRUN callback (62).
17:08:52.683 XRUN callback (63).
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
17:08:53.151 XRUN callback (1 skipped).
17:09:02.002 XRUN callback (65).
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
17:09:06.048 XRUN callback (66).
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackAudioDriver::ProcessGraphAsyncMaster: Process error
17:09:07.212 XRUN callback (1 skipped).
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
17:09:21.483 XRUN callback (68).
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
17:09:23.290 XRUN callback (1 skipped).
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
17:09:40.983 XRUN callback (70).
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
17:09:41.374 XRUN callback (3 skipped).
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
17:09:53.035 XRUN callback (74).
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
17:09:53.431 XRUN callback (1 skipped).
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
17:10:02.135 XRUN callback (76).
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
17:10:23.552 XRUN callback (77).
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
17:10:26.251 XRUN callback (79).
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
17:10:29.052 XRUN callback (80).
17:10:32.821 XRUN callback (81).
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
17:10:33.623 XRUN callback (1 skipped).
17:10:49.902 XRUN callback (83).
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
17:11:07.797 XRUN callback (84).
17:11:14.050 XRUN callback (85).
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
17:11:15.837 XRUN callback (1 skipped).
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
17:11:23.853 XRUN callback (87).
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
17:11:25.899 XRUN callback (2 skipped).
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
17:11:36.075 XRUN callback (91).
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
17:11:37.351 XRUN callback (93).
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
17:11:37.954 XRUN callback (4 skipped).
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackEngine::XRun: client = seq64_transport was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
17:11:39.962 XRUN callback (2 skipped).

**Comment by ahlstromcj** [comment]
I wonder why you get this error shown above:

Cannot use real-time scheduling (RR/55)(1: Operation not permitted)
JackClient::AcquireSelfRealTime error

I assume you're running seq24 using a2jmidid in order to feed it to JACK.  Have you tested the "legacy" sequencer64 in that same setup?  It would be telling me more if that one caused the XRUN issue as well.

I have been worried that there could be some I/O starvation in native JACK record/playback in seq64.  But what I see above indicates it's the JACK transport (which is a different JACK client from the native JACK MIDI support) that's acting up.

Anyway, can't do much about it until tonight, and any other info you can come up with would be great.

Thanks!

**Comment by layk** [comment]
It's the same behaviour with sequencer64 (-ed -am). 

Log from console:
 sequencer64 
[Reading rc configuration /home/.config/sequencer64/sequencer64.rc]
[Reading user configuration /home/.config/sequencer64/sequencer64.usr]
Cannot lock down 107335194 byte memory area (Cannot allocate memory)
[JACK server already started]
[JACK client:uuid is seq64_transport:10]
[JACK sync master]
Cannot use real-time scheduling (RR/55)(1: Operation not permitted)
JackClient::AcquireSelfRealTime error
[JACK sync enabled]
[JACK sync still enabled]
[JACK sync still enabled]

Btw in qjackctl i can see only one output port called ' sequencer64 (capture: seq64 out'. All the 'Midi output bus' settings have to be on '[0] 132:2 sequencer64:seq64 out 2' and therfore only midi channel selectable.

**Comment by layk** [comment]
Well xruns with my setup might be due to recent changes in fedora 24/25 system.d and limits.d configuration. I have to investigate. So ignore this issue for now.
https://bugzilla.redhat.com/show_bug.cgi?id=1189860
https://bugzilla.redhat.com/show_bug.cgi?id=1366880

**Comment by layk** [comment]
Hi
This issue is non sequencer64/seq64 related and can be closed. Everything works ok when i run seq64 or sequencer64 from menu. It seems that i can not run anything with realtime priorities from gnome-terminal or xterm. Yet to wind the correct place to put LimitRTPRIO and LimitMEMLOCK for consoles.
See : 
https://bugzilla.redhat.com/show_bug.cgi?id=1364332
[Service]
LimitRTPRIO=70
LimitMEMLOCK=4194304

Sorry for the noise.

**Comment by ahlstromcj** [comment]
If you haven't already, do something like this:

   http://jackaudio.org/faq/linux_rt_config.html

except your group name for audio/JACK might be different, and
you might want to use "unlimited" instead of a number for the memlock
setting.

This should make the settings system-wide.  You probably have to at least
logoff-logon.  You can verify the setup in a terminal window by:

$ ulimit -r
99

$ ulimit -l
unlimited

I have another weird issue, which also happens in legacy seq24, but doesn't
happen on my older 32-bit system.... If I start seq64 and the very first
thing I do is hit "Alt-F", the menu freezes and emits Gtk assertions.  If I
click in the main window first, or use the desired Ctrl key, it is fine.
This started happening recently; what got updated!?

-------- layk 03:41 Fri 14 Apr      --------

>Hi
>This issue is non sequencer64/seq64 related and can be closed. Everything works ok when i run seq64 or sequencer64 from menu. It seems that i can not run anything with realtime priorities from gnome-terminal or xterm. Yet to wind the correct place to put LimitRTPRIO and LimitMEMLOCK for consoles.
>See :
>https://bugzilla.redhat.com/show_bug.cgi?id=1364332
>[Service]
>LimitRTPRIO=70
>LimitMEMLOCK=4194304
>
>Sorry for the noise.
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/68#issuecomment-294134055

-- 
Beware of a tall blond man with one black shoe.

**Comment by layk** [comment]
I have done everything accordingly. See the bugzilla report. One now needs to do limit.conf or limits.conf for systemd to make gnome-terminal or xterm happy. This is a new thing. I managed to get things working on terminals making limit.conf and limits.conf on following places:
/etc/security/ (no affect anymore for terminals. Gnome shellis ok so opening from menu works.
/etc/systemd/system.conf.d /etc/systemd/user.conf.d
/etc/systemd/system/user@.service.d
/etc/systemd/system/user@1000.service.d/
~/.config/systemd/user/gnome-terminal-server.service.d/
And maybe some other places.
Anyway now i can start apps correctly from terminals.
The bug report in bugzilla is open. Hopefully they come into sane resolution and make it so that this sort of parameters will be configurable only in one place for the user. Like it was before in /etc/security/. This remains to be seen.

**Comment by ahlstromcj** [comment]
I did a lot of checking, too, which is always useful, so no worries.  I did find an important issue with the conversion of Note Off Velocity 0 to Note Off.... velocities from 0 to 15 were all converted to Note Off.  This was due to an issue someone raised in sequencer64-doc.  So you'll want the latest master or latest wip when you feel ready for adventure.  :-)
