### ISSUE TITLE
'pass through' button activates 'record incoming', doesn't pass MIDI through

### ISSUE THREAD

**Issue by milkmiruku** [ahlstromcj/sequencer64#69]
wip branch. Notes are added to the pattern from incoming MIDI data when either the 'pass through' or 'record incoming' buttons are pressed. When 'pass through' is selected, notes from incoming don't pass through, though clicking on the piano roll sends notes to the output.

**Comment by ahlstromcj** [comment]
I will check that out, once I get back from work.  Thanks!

**Comment by ahlstromcj** [comment]
Actually, I think I fixed this one, too, another obvious fat-finger bug in seqedit.  Let me know, otherwise I will revisit it this evening.

**Comment by milkmiruku** [comment]
Sorted, ta :)
