### ISSUE TITLE
Hovering pointer over an active toggle button gives the same graphic as an inactive button, confusing

### ISSUE THREAD

**Issue by milkmiruku** [ahlstromcj/sequencer64#70]
For the stateful buttons in the editor windows.

Maybe a lighter/darker shade of blue or a border would be more clear?

**Comment by ahlstromcj** [comment]
Well, that's partly theme-dependent, all the code does is set a binary value.  I will think about how to make it more obvious in the tooltips; either different text or just disable the tooltip?

In the meantime, you could perhaps tweak the Gtk2/3 theme you are using.  Sequencer64 used Gtk-2 for the GUI.

**Comment by milkmiruku** [comment]
Cheers, I'll look at the gtk theme.
