### ISSUE TITLE
On start; activated patterns become inactive on play (once)

### ISSUE THREAD

**Issue by milkmiruku** [ahlstromcj/sequencer64#71]
I start, select a number of patterns, press play, the transport starts but the patterns all deactivate.

Press stop, select a different pattern from before, same. Select one of the patterns that turned off last time and it stays active on play. Select a different pattern again and it deactivates on play, etc.

**Comment by ahlstromcj** [comment]
I'll look into it, but remember that, if the Song mode is active, or the Song Editor has focus, it controls what patterns are muted vs. unmuted.

**Comment by ahlstromcj** [comment]
Okay, I've kind of verified the bug.  Plus an unwanted interaction between the main window and the performance (song) window.  Thanks for the heads up!

**Comment by ahlstromcj** [comment]
Okay, I found the bug pretty quickly.  Yet another one of my (in)famous fat-fingers!  This one in perform :: toggle_other_seqs().

**Comment by milkmiruku** [comment]
Seems to be sorted, ta!
