### ISSUE TITLE
ghost mute group always coming back in rc

### ISSUE THREAD

**Issue by Animtim** [ahlstromcj/sequencer64#72]
Hi, I noticed an annoying issue with mute groups:
After just opening and closing the software, my first and last mute groups are changed from A to B.
A:
0 [1 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0]
...
31 [0 0 0 1 0 0 0 1] [0 0 0 1 0 0 0 1] [0 0 0 1 0 0 0 1] [0 0 0 1 0 0 0 1]

B:
1024       # group mute count
0 [1 1 1 0 1 1 1 1] [1 1 1 1 1 0 1 0] [1 1 1 1 1 1 1 1] [1 1 1 0 1 0 0 0]
...
31 [1 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0]

I'm not sure where those changes come from, I guess they are somehow hardcoded somewhere and reloaded for some reasons (it seems to not reload every time I close the software, but very often).

**Comment by ahlstromcj** [comment]
I think I found the bug, another fat-finger bug.  Check out the latest wip branch if you have the time. Thanks!  Your reports are very helpful!

**Comment by Animtim** [comment]
I tested master (I guess that's what you meant, the commit is pushed there ;) ).
It seems to improve as I can't reproduce the issue with just opening and closing the app, but it still can happen often after loading a file.

**Comment by Animtim** [comment]
Actually I can reproduce it every time by just loading the file TimeTest.midi from #73 and closing the app.
(except here line 31 looks exactly like line 0, with lots of 1...)

**Comment by ahlstromcj** [comment]
That data is actually included in that MIDI file.  Apparently it got "infected" before I fixed the bug.  I've added that file to contrib/midi and will use it to add/test a menu command to "Clear Group Mutes".  Seq24/64 save those to the "rc" file and "midi" file.  Thanks!

**Comment by Animtim** [comment]
Ah, good to know! 
By "Clear Group mutes", do you mean to reload them from the rc file? That would be a great option.

**Comment by ahlstromcj** [comment]
Good idea!  I'll add a "Reload" option as well!  The "Clear" will only remove them from the MIDI file, not the "rc" file.

**Comment by Animtim** [comment]
Great, thank you!

**Comment by ahlstromcj** [comment]
Well, Clear and Reload are in place (see master), but currently Clear does clear the file as well, so if you want to clear the mute-groups read from a MIDI file, one should do Clear followed by reload, or else keep the sequencer64.rc file backed up somewhere.

**Comment by Animtim** [comment]
Tested quickly, it works great and is actually how I expected it. Thanks a lot! I guess this one can be closed, unless you want some more testing.
