### ISSUE TITLE
egmentation fault on Arch64

### ISSUE THREAD

**Issue by funkmuscle** [ahlstromcj/sequencer64#8]
fresh pull but won't run..

$ sequencer64
[Reading rc configuration /home-g/.config/sequencer64/sequencer64.rc]
[JACK transport master]

(sequencer64:31463): Gtk-CRITICAL **: IA__gtk_widget_add_events: assertion 'GTK_IS_WIDGET (widget)' failed

(sequencer64:31463): Gtk-CRITICAL **: IA__gtk_widget_set_double_buffered: assertion 'GTK_IS_WIDGET (widget)' failed

(sequencer64:31463): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'GTK_IS_WIDGET (widget)' failed
Segmentation fault (core dumped)

**Comment by ahlstromcj** [comment]
Hmmm, I did a fresh pull of the master branch to a tmp directory and built
it here, and it runs with or without JACK.  Here are the (Debian) libraries I
have installed:

   libgtkmm-2.4-dev (2.24)  libgtk2.0-dev (2.24)  libgtk-3-dev
   
Some links indicate Qt (!) might be involved.  Does Qjackctl give a similar
error?

I also build it on CentOS fairly often, and run it.

Might take a little digging to understand this error.  Thanks for the
report, and if you find any other clues, please let me know.

Chris

-------- funkmuscle 16:45 Thu 07 Jan      --------

>fresh pull but won't run
>
>$ sequencer64
>[Reading rc configuration /home-g/config/sequencer64/sequencer64rc]
>[JACK transport master]
>
>(sequencer64:31463): Gtk-CRITICAL **: IA__gtk_widget_add_events: assertion 'GTK_IS_WIDGET (widget)' failed
>
>(sequencer64:31463): Gtk-CRITICAL **: IA__gtk_widget_set_double_buffered: assertion 'GTK_IS_WIDGET (widget)' failed
>
>(sequencer64:31463): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'GTK_IS_WIDGET (widget)' failed
>Segmentation fault (core dumped)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/8

-- 
Q:	What do you say to a New Yorker with a job?
A:	Big Mac, fries and a Coke, please!

**Comment by funkmuscle** [comment]
Qjackctl and other Qt programs all work fine

**Comment by Gimmeapill** [comment]
Couldn't reproduce either on Arch64. I'll double check dependencies. 
@funkmuscle You have gtk3 installed, right?

**Comment by funkmuscle** [comment]
yep gtk3 installed.. could it conflict with seq24?

**Comment by ahlstromcj** [comment]
It shouldn't conflict with seq24.  If you can, compile it for debug and run
it under gdb and see where it crashes. Gdb command 'bt' will show the call
stack.

**Comment by funkmuscle** [comment]
Type "apropos word" to search for commands related to "word"...
Reading symbols from sequencer64...done.
(gdb) bt
No stack.

**Comment by ahlstromcj** [comment]
First run the program (the "run" or "r" command).  That should crash.
You'll see the words "Segmentation fault".  That's a "segfault" for short.
Then do the "bt" command.  You can PageUp until you see frame 0 ("#0").
That's the last call before the crash.  The name of that function will
give a clue as to what submodule failed, and may provide a clue
to what cause the crash.

You can highlight the call stack and paste it into an email
if you want.  Sometimes the functions called before the crash provide
better clues.

Good luck!  Wish I could duplicate it here.  My guess is that
there is a dependency missing from your system, and once we figure
it out, I can add it to the INSTALL file and the configure.ac
script.

Chris


-------- funkmuscle 12:41 Fri 08 Jan      --------

>Type "apropos word" to search for commands related to "word"...
>Reading symbols from sequencer64...done.
>(gdb) bt
>No stack.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/8#issuecomment-170118586

-- 
Today is National Existential Ennui Awareness Day.

**Comment by funkmuscle** [comment]
(gdb) run
Starting program: /usr/local/bin/sequencer64 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[Reading rc configuration /home-g/.config/sequencer64/sequencer64.rc]
[New Thread 0x7fffe90fe700 (LWP 1525)]
[New Thread 0x7fffe88fd700 (LWP 1526)]
[New Thread 0x7ffff7ef7700 (LWP 1527)]
[New Thread 0x7fffe80fc700 (LWP 1528)]
[JACK transport master]
[New Thread 0x7fffe3fff700 (LWP 1529)]

(sequencer64:1521): Gtk-CRITICAL **: IA__gtk_widget_add_events: assertion 'GTK_IS_WIDGET (widget)' failed

(sequencer64:1521): Gtk-CRITICAL **: IA__gtk_widget_set_double_buffered: assertion 'GTK_IS_WIDGET (widget)' failed

(sequencer64:1521): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'GTK_IS_WIDGET (widget)' failed

(sequencer64:1521): Gtk-CRITICAL **: IA__gtk_widget_add_events: assertion 'GTK_IS_WIDGET (widget)' failed

(sequencer64:1521): Gtk-CRITICAL **: IA__gtk_widget_set_double_buffered: assertion 'GTK_IS_WIDGET (widget)' failed

(sequencer64:1521): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'GTK_IS_WIDGET (widget)' failed

(sequencer64:1521): Gtk-CRITICAL **: IA__gtk_widget_add_events: assertion 'GTK_IS_WIDGET (widget)' failed

(sequencer64:1521): Gtk-CRITICAL **: IA__gtk_widget_set_double_buffered: assertion 'GTK_IS_WIDGET (widget)' failed

(sequencer64:1521): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'GTK_IS_WIDGET (widget)' failed

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff73c4e21 in Gtk::Adjustment::signal_value_changed() ()
   from /usr/lib/libgtkmm-2.4.so.1
(gdb) bt
#0  0x00007ffff73c4e21 in Gtk::Adjustment::signal_value_changed() ()
   from /usr/lib/libgtkmm-2.4.so.1
#1  0x00007ffff7adef2e in seq64::perfnames::perfnames (this=0x746970, p=..., 
    parent=..., vadjust=..., __in_chrg=<optimized out>, __vtt_parm=<optimized out>)
    at perfnames.cpp:85
#2  0x00007ffff7adaffd in seq64::perfedit::perfedit (this=0x740ae0, p=..., 
    second_perfedit=<optimized out>, ppqn=-1, __in_chrg=<optimized out>, 
    __vtt_parm=<optimized out>) at perfedit.cpp:111
#3  0x00007ffff7acacbd in seq64::mainwnd::mainwnd (this=0x7fffffff9180, p=..., 
    allowperf2=<optimized out>, __in_chrg=<optimized out>, 
    __vtt_parm=<optimized out>) at mainwnd.cpp:121
#4  0x00000000004013ec in main (argc=1, argv=0x7fffffffe758) at sequencer64.cpp:110
(gdb)

**Comment by ahlstromcj** [comment]
Great! I'll check it out, looks important.

**Comment by ahlstromcj** [comment]
Try moving these lines from the perfnames.cpp constructor into perfnames::on_realize():

    m_vadjust.signal_value_changed().connect
    (
        mem_fun(*(this), &perfnames::change_vert)
    );

This might fix your segfault, but might just move it to another module.  I've noticed a couple
places where merely moving code either causes problems or fixes them.  Anyway, no
guarantees with this suggestion, but let me know if the call stack is different when you move
that code.  I tried it here, and I'll probably leave it in the on_realize() function.

**Comment by funkmuscle** [comment]
can't find 
perfnames::on_realize():

**Comment by ahlstromcj** [comment]
Seq_gtkmm2/src/perfnames.cpp line 294

**Comment by funkmuscle** [comment]
well it launched but you can't do anything with it!

**Comment by ahlstromcj** [comment]
Can you provide a little more information?

Anyway, I had broken the New pattern functionality, and it will be fixed
today.  Otherwise, you can load up MIDI files and edit and run them.

-------- funkmuscle 18:28 Sat 09 Jan      --------

>well it launched but you can't do anything with it!
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/8#issuecomment-170301355

-- 
You may get an opportunity for advancement today.  Watch it!

**Comment by funkmuscle** [comment]
yeah it opens midi files but crashes when I hit play....
either freezes or crash..

Program received signal SIGFPE, Arithmetic exception.
[Switching to Thread 0x7fffe3fff700 (LWP 1857)]
0x00007ffff779de7b in seq64::jack_timebase_callback (state=<optimized out>, 
    nframes=<optimized out>, pos=0x7ffff7fdc1c7, new_pos=<optimized out>, 
    arg=0x7fffffff8fa0) at jack_assistant.cpp:805
805             );
(gdb) bt
#0  0x00007ffff779de7b in seq64::jack_timebase_callback (state=<optimized out>, 
    nframes=<optimized out>, pos=0x7ffff7fdc1c7, new_pos=<optimized out>, 
    arg=0x7fffffff8fa0) at jack_assistant.cpp:805
#1  0x00007ffff31fe3b7 in ?? () from /usr/lib/libjack.so.0
#2  0x00007ffff31fd418 in ?? () from /usr/lib/libjack.so.0
#3  0x00007ffff3215a50 in ?? () from /usr/lib/libjack.so.0
#4  0x00007ffff20f84a4 in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007ffff68f813d in clone () from /usr/lib/libc.so.6
(gdb)

**Comment by ahlstromcj** [comment]
Thanks for the report!  It bugs out for me, too, when I run it with JACK
instead of ALSA.  Going over the JACK support code right now.  seq24
seems to handle JACK fine here.

-------- funkmuscle 09:01 Sun 10 Jan      --------

>yeah it opens midi files but crashes when I hit play....
>either freezes or crash..
>
>Program received signal SIGFPE, Arithmetic exception.
>[Switching to Thread 0x7fffe3fff700 (LWP 1857)]
>0x00007ffff779de7b in seq64::jack_timebase_callback (state=<optimized out>,
>    nframes=<optimized out>, pos=0x7ffff7fdc1c7, new_pos=<optimized out>,
>    arg=0x7fffffff8fa0) at jack_assistant.cpp:805
>805             );
>(gdb) bt
>#0  0x00007ffff779de7b in seq64::jack_timebase_callback (state=<optimized out>,
>    nframes=<optimized out>, pos=0x7ffff7fdc1c7, new_pos=<optimized out>,
>    arg=0x7fffffff8fa0) at jack_assistant.cpp:805
>#1  0x00007ffff31fe3b7 in ?? () from /usr/lib/libjack.so.0
>#2  0x00007ffff31fd418 in ?? () from /usr/lib/libjack.so.0
>#3  0x00007ffff3215a50 in ?? () from /usr/lib/libjack.so.0
>#4  0x00007ffff20f84a4 in start_thread () from /usr/lib/libpthread.so.0
>#5  0x00007ffff68f813d in clone () from /usr/lib/libc.so.6
>(gdb)
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/8#issuecomment-170371204

-- 
Someone whom you reject today, will reject you tomorrow.

**Comment by ahlstromcj** [comment]
Okay, merged some fixes into the master branch.  I thought I had botched the perform/JACK refactoring, and learned a lot about JACK trying to figure out what was going wrong.  But the fundamental issue was a long-standing bug in seq24.  The jack-position structure was not getting initialized, so it was filled with pseudo-random values that were good enough, on some people's systems, to get past the initial issue and start working.  The Sequencer64 code initialized the structure, but to zeroes. I added a call to jack_transport_query in the sync callback to fill in this structure as soon as JACK started, and that did the trick. 

There's still some odd behavior from the past.  I added to the File / Options / JACK/LASH tooltips to explain some things, and also updated the documentation in the Sequencer64-doc project.  Still more stuff to tweak; be sure to give more feedback, it's been very helpful.

**Comment by funkmuscle** [comment]
it plays, well I can load a midi file and hit play but it goes super fast with no sound

**Comment by ahlstromcj** [comment]
I just checked in 0.9.9.14 into the master/main branch.  I had a number of
errors in the JACK support, and also found a couple of bugs from the old
seq24.

It should work a bit better now.

I think you still have to expose the app's ALSA MIDI using the a2jmidid
application, if you want to play tunes through sequencer64 in a JACK
environment.  But it should sync to other JACKed apps now.

I think I've pretty much caught up with seq24 now, but there are still some
minor issues that existed in seq24.

Thanks for the bug reports!

Chris

-------- funkmuscle 15:46 Sun 24 Jan      --------

>it plays, well I can load a midi file and hit play but it goes super fast with no sound
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/8#issuecomment-174353969

-- 
Alimony and bribes will engage a large share of your wealth.

**Comment by funkmuscle** [comment]
sweet, we've got music!!

**Comment by danielappelt** [comment]
For me, this seems to work now. Maybe this issue could be closed?!

**Comment by funkmuscle** [comment]
yeah! y'all want me to do so?

**Comment by ahlstromcj** [comment]
After the Super Bowl :-)

**Comment by funkmuscle** [comment]
yep.. watching and making music

**Comment by danielappelt** [comment]
Excellent! I think only creators, assignees and project leaders can close issues.

**Comment by funkmuscle** [comment]
k

**Comment by ahlstromcj** [comment]
Anybody had a chance to try the latest master?  I think the transport and clock should be good now, and have been working on some interface improvements.

**Comment by danielappelt** [comment]
I am very busy these days. I will give it a try the following days and report back!

**Comment by Gimmeapill** [comment]
Sorry guys, not better here :-(

**Comment by ahlstromcj** [comment]
What version? What are the symptoms?  Can run it under gdb and get a
backtrace (stack dump)?  I've been beating on it pretty heavily and haven't
had any segfaults.  Are you getting them when starting up the Edit Event
editor?  Thanks.

-------- LX 01:12 Tue 16 Feb      --------

>Sorry guys, not better here :-(
>
>On Tue, Feb 16, 2016 at 9:53 AM, Daniel Appelt <notifications@github.com>
>wrote:
>
>> I am very busy these days. I will give it a try the following days and
>> report back!
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ahlstromcj/sequencer64/issues/8#issuecomment-184581476>
>> .
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/8#issuecomment-184589612

-- 
Writing is easy; all you do is sit staring at the blank sheet of paper until
drops of blood form on your forehead.
		-- Gene Fowler

**Comment by Gimmeapill** [comment]
No, I mean no time to test yet (replying to Daniel's comment) - sorry for the confusion.

**Comment by funkmuscle** [comment]
just did the latest pull.. all works fine here

**Comment by Gimmeapill** [comment]
I got it to crap out (and take jack down with it), but this looks like a different issue:
```
(sequencer64:10219): Gtk-CRITICAL **: IA__gtk_toggle_button_get_active: assertion 'GTK_IS_TOGGLE_BUTTON (toggle_button)' failed
[JACK sync already enabled!]
Cannot read socket fd = 8 err = Success
CheckRes error
JackSocketClientChannel read fail
[JACK sync now disabled]
```
rev 0.9.9.17.r0.ga3dd1fb

**Comment by ahlstromcj** [comment]
Cool :-* Took JACK down? Made it crash, or just stop responses? If you have
time, can you tell me what apps were connected?  Anyway, that error msg
should be helpful.  Thanks!

**Comment by ahlstromcj** [comment]
I could get that output by closing qjackctl while Seq64 was running with
JACK.  I couldn't get Seq64 to cause JACK itself to stop though.

That GTK assertion is annoying.  It doesn't happen with seq24, but the
code for setting up the buttons is essentially identical between
Seq64 and Seq24.  We're connecting signal_clicked, not signal_toggled.

Fume.  Will keep digging.

-------- LX 14:34 Tue 16 Feb      --------

>I got it to crap out (and take jack down with it), but this looks like a different issue:
>```
>(sequencer64:10219): Gtk-CRITICAL **: IA__gtk_toggle_button_get_active: assertion 'GTK_IS_TOGGLE_BUTTON (toggle_button)' failed
>[JACK sync already enabled!]
>Cannot read socket fd = 8 err = Success
>CheckRes error
>JackSocketClientChannel read fail
>[JACK sync now disabled]
>```
>rev 0.9.9.17.r0.ga3dd1fb
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/8#issuecomment-184902209

-- 
He jests at scars who never felt a wound.
		-- Shakespeare, "Romeo and Juliet, II. 2"

**Comment by Gimmeapill** [comment]
Well, I didn't see much: it was connected to zynaddsubfx and qjackctl. Both suddenly went missing (jackd was also stopped when I restarted qjackctl). I was playing with the jack transport sync options in seq64 when this happened. Could be Zyn as well - I was toying at the same time with a git build supposed to fix a crash :-{
I'll connect it into something officially released and see if I can reproduce the issue.

**Comment by ahlstromcj** [comment]
Interesting.  I had notice a package called "jack_demolition".  It looks
like it was meant for audio.  But it makes me want to add a build option
for adding some "demolition" code to the jack_assistant module, for
testing any app connected to JACK, as well as JACK itself.  

-------- LX 01:39 Wed 17 Feb      --------

>Well, I didn't see much: it was connected to zynaddsubfx and qjackctl. Both
>suddenly went missing (jackd was also stopped when I restarted qjackctl). I
>was playing with the jack transport sync options in seq64 when this
>happened. Could be Zyn as well - I was toying at the same time with a git
>build supposed to fix a crash :-{ I'll connect it into something officially
>released and see if I can reproduce the issue.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/8#issuecomment-185118800

-- 
You will be reincarnated as a toad; and you will be much happier.

**Comment by danielappelt** [comment]
Or you might go for a fuzz effect doing [fuzz testing](https://en.wikipedia.org/wiki/Fuzz_testing).

**Comment by Gimmeapill** [comment]
It's better now, I couldn't get it to crash (0.9.9.18.r0.gdb85f3d)

**Comment by funkmuscle** [comment]
this isn't a problem guys but any icons in the works for seq64?

**Comment by ahlstromcj** [comment]
There's a couple of simple icons in resources/pixmaps:  seq64.xpm and
seq64_32.xpm.  Nothing to write home about.  

You have any ideas for a logo?  Or are you talking about icons to show in
each seq64 window?  I need inspiration!  :-)

-------- funkmuscle 15:18 Wed 02 Mar      --------

>this isn't a problem guys but any icons in the works for seq64?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/8#issuecomment-191488938

-- 
Day of inquiry.  You will be subpoenaed.

**Comment by funkmuscle** [comment]
nah just a desktop icon

**Comment by ahlstromcj** [comment]
I added a "resources/icons" directory with a few new (and simple) icons;
the smallest one is in the "resources/pixmaps" directory.

Currently only in the "fixups" branch.

-------- funkmuscle 17:57 Wed 02 Mar      --------

>nah just a desktop icon
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64/issues/8#issuecomment-191536755

-- 
Courage is your greatest present need.

**Comment by funkmuscle** [comment]
fails to build now:
op source-directory 'top_srcdir' is .
* * * * * All build items completed * * * * *
make[2]: Entering directory '/tmp/yaourt-tmp-harv/aur-sequencer64-git/src/sequencer64'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/tmp/yaourt-tmp-harv/aur-sequencer64-git/src/sequencer64'
make[1]: Leaving directory '/tmp/yaourt-tmp-harv/aur-sequencer64-git/src/sequencer64'
install: creating directory '/tmp/yaourt-tmp-harv/aur-sequencer64-git/pkg/sequencer64-git/usr/share/pixmaps'
install: cannot stat 'debian/sequencer24.xpm': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...

**Comment by ahlstromcj** [comment]
For now, go into the "debian" directory and copy sequencer64.xpm to
sequencer24.xpm; not sure why it is failing, though.

**Comment by funkmuscle** [comment]
k, I will keep messin' with it..

**Comment by danielappelt** [comment]
Which PKGBUILD are you using @funkmuscle? The one from AUR should only fetch tagged versions, and the latest one 0.9.9.18 should still come with debian/sequencer24.xpm.
Furthermore, I would suggest closing this bug as we are going quite off-topic here.

**Comment by funkmuscle** [comment]
I will close this.. I'm using the current git PKGBUILD by the way!
