### ISSUE TITLE
Resizing notes not possible in fruity mode

### ISSUE THREAD

**Issue by yousefamar** [ahlstromcj/sequencer64#90]
According to §2.2.5.5 of the manual, it should be possible to resize notes by clicking and dragging their edges. As far as I can tell, this doesn't seem to work. The only way to do so is to switch to seq24 mode and middle-mouse drag. Is this a bug or am I doing something wrong? Any tips much appreciated.

**Comment by ahlstromcj** [comment]
This one has proved puzzling, still need to beat on it some more.

**Comment by ahlstromcj** [comment]
I finally figured it out; I was copying a snapped time value which broke right-side note handling.  There is still an issue, present in Seq24, where the left side is not handled for resizing, but left side click drag will at least remove the note.  See version 0.94.3 in the master branch.
