### ISSUE TITLE
another seq24 fork

### ISSUE THREAD

**Issue by F0rth** [ahlstromcj/sequencer64#97]
Hi,

I just found another seq24 fork https://github.com/oli-kester/kepler34
( screenshots here http://imgur.com/a/wN2AA )
There are perhaps some ideas or code to borrow.
Thank you for your hard work.

F.

**Comment by ahlstromcj** [comment]
Thanks for the heads up.  However, I can't build it using the instructions, got some weird errors.  The screenshots show some things I'd be interested in adopting (tabbed views, though some users have said they don't like them, and I've wanted to replace the hardwired mainwid fonts with something better, but just as fast, if possible).   I think I'll try to touch base with the author.  Thanks for the strokes!  This project has gone on far longer than I anticipated in the very beginning, and the users who give feed back give me good ideas and keep me motivated to add new features and yet preserve the tight nature of seq24.

**Comment by F0rth** [comment]
I didn't have any issue getting it compiling and working on a debian 9 box (sorry for the late answer, was busy irl).

**Comment by ahlstromcj** [comment]
I got  it to build, but it has some segfaults. I'm merging it into a new
Windows branch,  but am currently trying to merge Kepler34 features into
Seq64 before getting the Qt 5 code working. Then slowly getting Seq64
features implemented using Qt. So much!
